== Johdanto
Paikkatietoalusta-hankeen tavoitteena on yhtenäistää valtion, maakuntien ja kuntien paikkatiedot ja
tuoda ne myös yritysten ja yhteisöjen saataville. Vuonna 2017 alkanut hanke on osa hallituksen Digitalisoidaan julkiset
palvelut -kärkihankekokonaisuutta. Tavoitteena on yhtenäistää ja parantaa julkisen hallinnon sähköisiä
palveluita, parantaa ja tehdä läpinäkyvämmäksi tietopohjaista päätöksentekoa sekä säästää kustannuksia
julkisessa hallinnossa.

Ajantasaisten ja riittävän tarkkojen metatietojen rooli paikkatietoaineistojen löytämisessä sekä
niiden soveltuvuuden ja laadun arvioinnissa on tärkeä. Vain laadukkaan ja hyvin ylläpidetyn metatiedon
avulla voidaan toteuttaa hyvin toimivia ja täsmällisiä tuloksia antavia aineiston hakupalveluita,
kuten Paikkatietoalustan ontologioiden hyödyntämiseen ja koneoppimiseen perustuva älykäs hakukone (<<alykas_haku>>).

Tämän dokumentin kuvaama metatietoprofiili laaditiin osana Paikkatietoalusta-hankkeen
keskeisten PTA-aineistojen metatietojen laadun ja kattavuuden parantamiseen tähtäävää työtä.
Paikkatietoalustan nykyisten ja potentiaalisten käyttäjien metatiedon käyttöön ja paikkatietoaineistojen
löytämiseen liittyvien tarpeiden selvittämiseksi tehtiin käyttötarveselvitys elo-lokakuussa 2018.
Selvityksen aikana yksilö- ja
ryhmähaastatteluihin osallistui yhteensä 22 henkilöä seitsemästä eri julkishallinnon ja yksityisen sektorin
organisaatiosta (<<kayttotarveselvitys>>). Käyttötarveselvityksen tuloksena syntyi raportti, joka kuvaa paikkatietoaineistojen hankintaa,
arviointia ja käyttöä haastatelluissa organisaatioissa, sekä Paikkatietoalustaan ja julkishallinnon
ylläpitämiin ja julkaisemiin paikkatietoaineistoihin liittyviä onnistumisia ja parannuskohteita.

=== PTA-metatietoprofiilin käyttäjät ja käyttötarkoitus
Paikkatietoalustan metatietoprofiilin tarkoituksena on
ohjata Paikkatietoalustalla julkaistavien aineistojen tuottajia kuvaamaan aineistojen metatiedot tavalla,
joka helpottaa aineistojen löytämistä ja niiden arviointia. PTA-metatietoprofiili ei sellaisenaan
ole tarkoitettu ohjeeksi tiedontuottajille aineistojen metatietojen tarkoituksenmukaista kuvaamista varten. Useimmat
Paikkatietoalustan käyttäjät ja monet tiedontuottajatkaan eivät suoraan
lue tai kirjoita XML-muotoisia metatietokuvauksia, vaan he hyödyntävät web- tai työpöytäsovelluksia,
jotka esittävät metatietokentät helpommin luetavassa muodossa ja helpottavat metatietojen muokkausta niille
asetettujen vaatimusten mukaisiksi.

Tässä dokumentissa kuvattu metatietoprofiili on ensisijaisesti tarkoitettu kuvaamaan PTA-aineistojen
metatiedon välittämisen minimitietosisältö ja -muoto teknisen yhteentoimivuuden takaavalla tasolla. Vaatimukset on laadittu silmälläpitäen
sekä käyttötapauksia, joissa PTA-aineistojen metatieto tuodaan Paikkatietoalustaan tiedontuottajien omista tai muista ulkopuolisista
tietojärjestelmistä, että käyttötapauksia, joissa metatiedot kuvataan ja niitä ylläpidetään Paikkatietoalustan tarjoamilla
työvälineillä ja sovelluksilla. Osa vaaditusta metatietosisällöstä, kuten Paikkatietoalustan Laatuvahti-palvelun
laatutestien tulokset (ks. <<#vaatimus-pta-vaatimuksenmukaisuus,vaatimukset/vaatimus-pta-vaatimuksenmukaisuus>>), on
suunniteltu sisällöksi, jonka Paikkatietoalusta tuottaa automaattisesti osaksi aineiston metatietokuvausta. Muutoinkin
on tavoitteena, että Paikkatietoalustan aineistojen metatietoja ylläpidetään mahdollisimman automaattisesti.

Paikkatietoalustan metatietoprofiili on tässä dokumentissa kuvattu käyttäen <<ISO_19139>>-standardin
mukaista metatietojen XML-tietorakennetta. Vaatimukset ja suositukset
on esitetty käyttäen <<XPath_20>>-kyselykielisiä ilmauksia, jotta niiden merkitys jäisi
mahdollisimman vähän tulkinnanvaraiseksi, eikä erillisiä tulkintaohjeista tarvita teknisen yhteentoimivuuden
takaamiseksi. Koska asetettujen vaatimusten kieli jää näin hyvin tekniseksi, on suositeltavaa huomioida
suoraan tiedontuottajille tarkoitetun ohjeistuksen tarpeet Paikkatietoalustan metatiedonkäsittelyvälineiden
kehityksessä ja dokumentoinnissa.

=== PTA-kohtaisten metatietovaatimusten perustelut

Käyttötarveselvityksen tuloksia on hyödynnetty määriteltäessä PTA-metatietoprofiilin vaatimuksia.
Metatietovaatimusten määrittely on tasapainottelua juuri sopivan kuvaustason saavuttamiseksi:
Uusien pakollisten metatietoelementtien vaatiminen tai niiden kuvaustekniikan tarkentaminen aiheuttaa
lisävaatimuksia myös metatietoa käsitteleville tietojärjestelmille, ja siten usein lisäkustannuksia.
Toisaalta puutteellinen tai epätarkka ohjeistus johtaa metatietokuvauksiin, joiden tiedot ovat
puutteellisia tai joiden tietojen automaattinen hyödyntäminen on vaikeaa, ja joiden laatimisen
kustannus-hyötysuhde jää matalaksi.

Erityisesti PTA-metatietoprofiilin laadinnassa on pyritty ratkaisemaan seuraavia haastatteluissa
ilmenneitä metatietojen käytön ongelmia ja puutteita:

* Käyttäjien on vaikeaa hahmottaa mitä aineistoja Paikkatietoalustan kautta on saatavilla, millaisin
käyttöehdoin ne saa käyttöön ja millaisia mahdollisia rajoitteita ne sisältävät. Tähän vastaa
<<#vaatimus-kayton-rajoitukset,Vaatimus 10>>.

* Paikkatietoalustan ja Paikkatietohakemiston kautta aineistoa etsittäessä on usein vaikeaa
selvittää miten tiettyyn aineistoon pääsee käsiksi. Hakupalvelusta pitäisi suoraan päästä
lataamaan vähintään näyte aineistosta ja lisäksi tulisi selkeästi tarjota tarvittava tieto aineistojen
lataamiseksi erilaisia rajapintapalveluja käyttäen. Tähän vastaavat Vaatimukset
<<#vaatimus-latauspalvelu-linkki,11>>, <<#vaatimus-latauspalvelu-linkki-predefined-wfs,12>>,
<<#vaatimus-latauspalvelu-linkki-predefined-atom,13>>, <<#vaatimus-latauspalvelu-linkki-wcs,14>> ja
<<#vaatimus-latauspalvelu-linkki-sos,15>>.

* Hakupalvelut eivät ymmärrä hakusanojen taivutusmuotoja ja niihin liittyviä käsitteitä riittävän hyvin, mikä
johtaa puutteelisten tai virheellisten halutulosten esittämiseen. Myös aineistojen tuottajien on
hankalaa tietää mitä sanastoja ja avainsanoja aineistojen metatiedoissa tulisi käyttää. Tarvitaan
nykyistä parempaa ohjeistusta avainsanojen ja -sanastojen käytöstä osana paikkatietoaineitojen
metatietoja. Tähän vastaavat Vaatimukset <<#vaatimus-asiasana-ankkuri, 7>>,
<<#vaatimus-asiasanasto-ankkuri, 8>> ja <<#vaatimus-pta-asiasanat, 9>>.

* Metatietojen perusteella on toisinaan vaikea tietää milloin aineisto on kerätty ja minkä hetken tilannetta
se kuvaa. Tähän vastaavat Vaatimukset <<#vaatimus-paivitystiheys,5>> ja
<<#vaatimus-viimeinen-paivitys,6>> sekä <<#suositus-aikaviite,Suositus 2>>.

* Metatietojen perusteella on usein vaikeaa tietää minkälainen aineiston yksityiskohtaisuuden tai
spatiaalisen tarkkuuden taso on. Vektoripohjaisten aineistojen yksityiskohtaisuuden
arviointi nykyisten metatietokuvausten perusteella on vaikeaa, ja erityisen vaikeaa tämä tieto
on päätellä automaattisesti, sillä mahdollinen yksityiskohtaisuudesta kertova tieto on
usein annettu vapaatekstinä. Tähän vastaa <<#suositus-yksityiskohtaisuus-luokittelu, Suositus 3>>.

* Paikkatietoaineistojen sisällön laatua on vaikeaa arvioida metatietojen perusteella. Käytännössä
arvioinnissa luotetaan usein siihen, että kun aineiston on tuottanut ja/tai julkaissut laadukkaista
aineistoista tunnettu taho, niin oletetaan sen täyttävän järkevät laatuvaatimukset.
<<#vaatimus-pta-vaatimuksenmukaisuus, Vaatimus 16>> liittyy laatutestien
tulosten ilmaisemiseen osana PTA-aineistojen metatietoja.

PTA-metatietoprofiili perustuu kansainvälisiin <<ISO_19115>> - ja <<ISO_19139>> -standardeihin
ja niitä tarkentavien INSPIRE-direktiivin metatieto-ohjeistus - (<<TG_MD_20>>) ja
Julkishallinnon suositus <<JHS_158>> -dokumenttien vaatimuksin ja suosituksiin. Vaatimukset
<<#vaatimus-metatiedon-kieli,1>>, <<#vaatimus-metatiedon-tunnus,2>>, <<#vaatimus-tm35-tunnus,3>> ja
<<#vaatimus-aineiston-tunnus,4>> sekä <<#suositus-aineiston-pta-tunnus, Suositus 1>> tarkentavat
mainittujen ohjeistusten teknisiä vaatimuksia hakutoimintojen ja aineistojen ylläpidon
helpottamiseksi ja käyttövarmuuden parantamiseksi.
