== Vaatimusluokka PTA-aineisto
Paikkatietoalusta-tietoaineistojen metatietojen tulee olla kuvattu seuraavien dokumenttien tai niiden osien
sisältämien vaatimusten mukaisesti:

* 'Technical Guidance for the implementation of INSPIRE dataset and service metadata based on ISO/TS 19139:2007', vaatimustenmukaisuusluokka 'Conformance Class 2: metadata/2.0/isdss' <<TG_MD_20>>
* 'JHS 158 Paikkatietoaineistojen ja -palveluiden metatiedot', JHS-metatietoprofiili <<JHS158>>

Lisäksi PTA-aineineistojen metatietojen kuvaamisessa tulee noudattaa tässä luvussa kuvattuja PTA-kohtaisia
lisävaatimuksia.

[cols="1,4",width="90%"]
|===
2+|*Vaatimusluokka* {set:cellbgcolor:#CACCCE}
2+|`vaatimus/luokka-pta-aineisto` {set:cellbgcolor:#FFFFFF}
|Kohde |Metatietokuvaus
|Riippuvuus |http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/isdss
|Riippuvuus |http://www.jhs-suositukset.fi/suomi/jhs158/jhs-metatietoprofiili
|*Vaatimus 1* {set:cellbgcolor:#CACCCE} | `vaatimus/luokka-pta-aineisto/vaatimus-1` +
requirement description {set:cellbgcolor:#FFFFFF}
|*Vaatimus 2* {set:cellbgcolor:#CACCCE} | `vaatimus/luokka-pta-aineisto/vaatimus-2` +
requirement description {set:cellbgcolor:#FFFFFF}
|*Vaatimus 3* {set:cellbgcolor:#CACCCE} | `vaatimus/luokka-pta-aineisto/vaatimus-3` +
requirement description
{set:cellbgcolor:#FFFFFF}
|===

=== Yleiset metatiedon XML-koodaukseen kohdistuvat vaatimukset
Alla on listattu täydellisyyden vuoksi yleiset <<ISO 19139>>-standardin mukaisen
metatiedon koodaukseen liittyvät INSPIRE-vaatimukset. Näiden vaatimusten tarkemmat kuvaukset löytyvät
dokumentista <<TG_MD_20>>.

[cols="1,4",width="90%"]
|===
|*Numero* {set:cellbgcolor:#CACCCE}| *Tunnus*
|TG{nbsp}Requirement{nbsp}C.1 {set:cellbgcolor:#FFFFFF}| http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/xml-schema
|TG{nbsp}Requirement{nbsp}C.2 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/root-element
|TG{nbsp}Requirement{nbsp}C.3 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/code-list-value
|TG{nbsp}Requirement{nbsp}C.4 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/free-text
|===

=== Metatiedon tunnistamistiedot
Alla on listattu täydellisyyden vuoksi metatiedon tunnistamistietoihin
liittyvät INSPIRE-vaatimukset. Näiden vaatimusten tarkemmat kuvaukset löytyvät
dokumentista <<TG_MD_20>>.

[cols="1,4",width="90%"]
|===
|*Numero* {set:cellbgcolor:#CACCCE}| *Tunnus*
|TG{nbsp}Requirement{nbsp}C.5 {set:cellbgcolor:#FFFFFF}| http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/metadata-language-code
|TG{nbsp}Requirement{nbsp}C.6 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/md-point-of-contact
|TG{nbsp}Requirement{nbsp}C.7 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/md-date
|TG{nbsp}Requirement{nbsp}C.19 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/bounding-box
|TG{nbsp}Requirement{nbsp}1.1 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/resource-type
|===

WARNING: TBA: JHS 158 -profiilin vaatimukset?

* JHS 158: md-date aina metatiedon luontipvm, INSPIREssä viimeisin muokkaus, tai luonti, jos ei muokattu

==== Metatiedon kieli ja monikielisyys
INSPIRE-vaatimus TG Requirement C.5 vaatii ilmaisemaan luonnollisen kielen, jolla metatiedon vapaatekstisisältö on
kuvattu. Lisäksi vaatimus TG Requirement C.4 esittää kolme sallittua vaihtoehtoa vapaateksti-arvoisten metatietoelementtien
ilmaisemiseen.

[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{counter:req}* {set:cellbgcolor:#CACCCE}| `vaatimus/luokka-pta-aineisto/vaatimus-metatiedon-kieli` +
{set:cellbgcolor:#FFFFFF}
Mikäli PTA-aineiston metatietokuvaus on saatavilla useammalla kuin yhdellä kielellä, tulee niistä yksi valita
metatiedon kieleksi INSPIRE-vaatimuksen TG Requirement C.5 mukaisesti.

XPath-kyselyn
`/pass:[*]/gmd:locale/gmd:PT_Locale[@id]`
tulee palauttaa yllä määritellyn metatiedon kielen lisäksi metatietokuvauksessa
käytettyjen kieli- ja merkistöyhdistelmien tiedot. +

Kunkin monikielisen vapaatekstielementin
tyyppi on määriteltävä uudelleen dynaamisella tyypityksellä (attribuutti `xsi:type="gmd:PT_FreeText_PropertyType"`) INSPIRE-vaatimuksen
TG Requirement C.4 vaihtoehdon 3 mukaisesti. +

XPath-kyselyn
`//gmd:PT_FreeText/gmd:textGroup/gmd:LocalisedCharacterString[@locale='#<locale_id>']`
tulee palauttaa arvot niille vapaatekstikentille, jotka on annettu eri kielellä kuin
yllä määritelty metatiedon kieli. Merkkijonon `<locale_id>` arvo on oltava kyseisen kieli- ja merkistöyhdistelmän
kuvaavan elementin `/pass:[*]/gmd:locale/gmd:PT_Locale` attribuutin `id` arvo.

|===

==== Metatietokuvauksen yksilöivä tunnus

<<TG_MD_20>> suosittelee pysyvien ja globaalisti yksilöivien tunnusten antamista INSPIRE-aineistojen metatietokuvauksille käyttäen elementtiä
`gmd:fileIdentifier`.

[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{counter:req}* {set:cellbgcolor:#CACCCE}| `vaatimus/luokka-pta-aineisto/vaatimus-metatiedon-tunnus` +
{set:cellbgcolor:#FFFFFF}
PTA-aineistojen <<ISO_19139, ISO 19139>> -muotoisissa metatietokuvauksille on annettava globaalisti
yksilöivä merkkijonomuotoinen UUID-tunnus. XPath-kyselyn
`/pass:[*]/gmd:fileIdentifier`
tulee palauttaa näin määritelty metatiedon yksilöivä tunnus.
|===

=== Vertausjärjestelmä (referenceSystemInfo)

Alla on listattu täydellisyyden vuoksi vertausjärjestelmään
liittyvät INSPIRE-vaatimukset. Näiden vaatimusten tarkemmat kuvaukset löytyvät
dokumentista <<TG_MD_20>>.

[cols="1,4",width="90%"]
|===
|*Numero* {set:cellbgcolor:#CACCCE}| *Tunnus*
|TG{nbsp}Requirement{nbsp}2.1 {set:cellbgcolor:#FFFFFF}| http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/isdss/crs
|TG{nbsp}Requirement{nbsp}2.1 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/isdss/crs-id
|TG{nbsp}Requirement{nbsp}2.3 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/isdss/temportal-rs
|===

=== Resurssin tunnistamistiedot (indentificationInfo)

Alla on listattu täydellisyyden vuoksi resurssin tunnistamistietoihin
liittyvät INSPIRE-vaatimukset. Näiden vaatimusten tarkemmat kuvaukset löytyvät
dokumentista <<TG_MD_20>>.

[cols="1,4",width="90%"]
|===
|*Numero* {set:cellbgcolor:#CACCCE}| *Tunnus*
|TG{nbsp}Requirement{nbsp}C.8 {set:cellbgcolor:#FFFFFF}|http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/resource-title
|TG{nbsp}Requirement{nbsp}C.9 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/resource-abstract
|TG{nbsp}Requirement{nbsp}C.10 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/responsible-organisation
|TG{nbsp}Requirement{nbsp}C.11 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/temporal-reference
|TG{nbsp}Requirement{nbsp}C.12 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/max-1-date-of-creation
|TG{nbsp}Requirement{nbsp}C.13 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/max-1-date-of-last-revision
|TG{nbsp}Requirement{nbsp}C.14 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/metadata/2.0/req/common/temporal-extent
|TG{nbsp}Requirement{nbsp}C.15 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/metadata/2.0/req/common/keyword-originating-cv
|TG{nbsp}Requirement{nbsp}C.16 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/metadata/2.0/req/common/group-keywords-by-cv
|TG{nbsp}Requirement{nbsp}C.17 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/metadata/2.0/req/common/limitations-on-public-access
|TG{nbsp}Requirement{nbsp}C.18 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/metadata/2.0/req/common/conditions-for-access-and-use
|TG{nbsp}Requirement{nbsp}1.2 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/only-one-md-data-identification
|TG{nbsp}Requirement{nbsp}1.3 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/dataset-uid
|TG{nbsp}Requirement{nbsp}1.4 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/inspire-theme-keyword
|TG{nbsp}Requirement{nbsp}1.5 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/spatial-resolution
|TG{nbsp}Requirement{nbsp}1.6 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/resource-language
|TG{nbsp}Requirement{nbsp}1.7 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/topic-category
|TG{nbsp}Requirement{nbsp}2.4 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/isdss/spatial-representation-type
|TG{nbsp}Requirement{nbsp}2.5 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/isdss/character-encoding
|===

Näiden vaatimusten lisäksi PTA-aineistoja koskevat seuraavien alilukujen lisävaatimukset.

==== Aineiston yksilöivä tunnus

INSPIRE-aineistoille on annettava yksilöivä URI-muotoinen tunnus (<<TG_MD_20>>, TG Requirement 1.3). Lisäksi
suositellaan, että aineiston tunnus on pysyvä (TG Recommendation 1.3), että käytettävä URI-tunnus on
HTTP- tai HTTPS-protokollan mukainen URL-osoite (TG Recommendation 1.2), ja että aineiston tunnus tulisi
ilmaista käyttäen `gmd:MD_Identifier`-elementtiä (TG Recommendation 1.1).

[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{counter:req}* {set:cellbgcolor:#CACCCE}| `vaatimus/luokka-pta-aineisto/vaatimus-aineiston-tunnus` +
{set:cellbgcolor:#FFFFFF}
PTA-aineistolle tulee antaa pysyvä URL-muotoinen tunnus. URL-osoitteen protokollan tulee olla joko `HTTP` tai `HTTPS`,
ja sen tulee osoittaa ko. protokollan mukaisesti joko suoraan tai uudelleenohjauksen avulla julkisessa Internetissä sijaitsevaan dokumentiin, joka antaa
lisätietoja kuvatusta aineistosta. Palautettava dokumentti voi olla, mutta sen ei tarvitse olla aineiston
metatietokuvaus.

XPath-kyselyn +
`/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:citation/pass:[*]/gmd:identifier/gmd:MD_Identifier/gmd:code/pass:[*]/text()`
tulee palauttaa aineiston URL-tunnus.
|===

[width="90%",cols="2,6"]
|===
|*Suositus{nbsp}{counter:rec}* {set:cellbgcolor:#CACCCE}| `vaatimus/luokka-pta-aineisto/suositus-aineiston-pta-tunnus` +
{set:cellbgcolor:#FFFFFF}
Mikäli PTA-aineistolle ei Paikkatietoalustan ulkopuolella ole annettu INSPIRE-vaatimukset ja yllä kuvatun Vaatimuksen 2
ehdot täyttävää URL-muotoista tunnusta, on suositeltavaa käyttää aineiston yksilöivänä tunnuksena Paikkatietoalustan
tuottamaa URL-osoitetta, joka osoittaa Paikkatietoalustan hakupalvelun ko. aineiston tietokorttisivulle.
Tämän URL-osoitteen tulisi olla mahdollisimman pysyvä pitkällä aikavälillä.

Mikäli aineiston tietokorttisivun osoitetta
muutetaan tulevaisuudessa, aiemmin aineistotunnuskäytössä olleiden URL-osoitteiden tulisi uudelleenohjautua
tietokorttisivun uuteen osoitteeseen.

Mikäli aineiston poistetaan Paikkatietoikkunasta tai se korvataan toisella
aineistolla, jolla on eri tunnus, tulisi poistetun aineiston URL-tunnuksen osoittaa sivuun, jossa kerrotaan että
ko. aineisto ei ole enää saatavilla Paikkatietoikkunan kautta.
|===

==== Aineiston aikaviitteet
[#maintenance-and-update-frequency]
[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{counter:req}* {set:cellbgcolor:#CACCCE}| `vaatimus/luokka-pta-aineisto/vaatimus-paivitys-tiheys` +
{set:cellbgcolor:#FFFFFF}
Mikäli aineistolle on määritelty säännöllinen päivitystiheys, ja se voidaan ilmaista
ISO 19139 -standardin koodilistan `MD_MaintenanceFrequencyCode` arvojen avulla, on
se annettava metatiedossa. Seuraavan XPath-kyselyn tulee tällöin
palauttaa aineiston päivitystiheystieto:
`/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:resourceMaintenance/pass:[*]/gmd:maintenanceAndUpdateFrequency/gmd:MD_MaintenanceFrequencyCode`

Koodin on oltava yksi ISO 19139 -standardin koodilistan `MD_MaintenanceFrequencyCode` sallituista arvoista.
|===

[NOTE]
====
INSPIRE <<TG_MD_20>> TG Requirement C.11:ssa vaaditaan, että aineiston aikaviite annetaan vähintään yhdellä
seuraavista tavoista:

* ajallinen kattavuus (temporal extent),
* julkaisupäivämäärä,
* viimeisin päivitysajankohta, tai
* luontiajankohta.

Siten pelkkä aineiston päivitystiheyden kuvaaminen ei riitä täyttämään INSPIRE-vaatimuksia aikaviitteiden osalta.
====

[width="90%",cols="2,6"]
|===
|*Suositus{nbsp}{counter:rec}* {set:cellbgcolor:#CACCCE}| `vaatimus/luokka-pta-aineisto/suositus-aikaviite` +
{set:cellbgcolor:#FFFFFF}
Mikäli aineistolle on kuvattu metatiedossa päivitystiheys, eikä aineiston
viimeisintä päivitysajankohtaa ole mielekästä pitää ajantasalla, on
suositeltavaa antaa joko aineiston ajallinen kattavuus tai sen luontiajankohta.
|===

[#date-of-last-revision]
[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{counter:req}* {set:cellbgcolor:#CACCCE}| `vaatimus/luokka-pta-aineisto/vaatimus-viimeinen-paivitys` +
{set:cellbgcolor:#FFFFFF}
Mikäli aineistolle ei ole metatiedossa kuvattu säännöllistä päivitystiheyttä (ks. <<maintenance-and-update-frequency, Vaatimus 1>>), on
aineiston viimeisin päivitysajankohta on annettava. Seuraavan XPath-kyselyn tulee tällöin palauttaa aineiston
viimeisin päivitysajankohta päivän tarkkudella:
`/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:citation/pass:[*]/gmd:date[./pass:[*]/gmd:dateType/pass:[*]/@codeListValue='revision']/pass:[*]/gmd:date[1]`
|===

==== Sijainnillinen yksityiskohtaisuus

INSPIRE-vaatimuksen TG Requirement 1.5 mukaisesti aineiston erotyskyky on annettava, mikäli se on ko. aineistolle
saatavissa. Erotuskyky tulee tällöin antaa joko mittakaavana (equivalent scale) tai näytetiheytenä
(resolution distance).

Mittakaava tai näytetiheys ei ole kaikista tarkoituksenmukaisin tapa ilmaista kaikkien PTA-aineiston
yksityiskohtaisuuden tasoa. Esimerkiksi rakennetun ympäristön CityGML-aineistoissa yksityiskohtaisuus
ilmaistaan CityGML-standardissa määritellyillä level of detail -tasoilla (LOD0 - LOD4) <<CityGML>>.
PTA-metatietokuvauksessa suositellaan tällaisissa tapauksissa käytettäväksi
vaatimuksenmukaisuus-viittausta osana laatutietoja (ks. <<rec-lod, Suositus 2>>)

==== Avainsanat

INSPIRE-suositukset TG Recommendation C.8 ja C.9 suosittelevat `gmx:Anchor`-elementin ja URI-tunnusten
käyttöä avainsanoihin ja sanastoihin viittaamisessa. PTA-aineistojen metatietokuvauksessa tämä viittaustapa
on pakollinen, mikäli yleisesti tunnettu URI-tunnus käytettyihin sanastoihin ja avainsanoihin on olemassa.

[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{counter:req}* {set:cellbgcolor:#CACCCE}| ``vaatimus/luokka-pta-aineisto/vaatimus-asiasana-ankkuri`` +
{set:cellbgcolor:#FFFFFF}
Metatietokuvauksessa aineistoa kuvaavat avainsanat on ilmaistava sekä
itse avainsanan sisältävänä tekstinä että ko. avainsanaan URI-tunnuksena,
mikäli yleisesti tunnettu, pysyvä URI-tunnus ko. asiasanalle on olemassa.

Mikäli asiasanan URI-tunnus on käytettävissä yllämainituin ehdoin, tulee tekstimuotoinen avainsana
ilmaista elementin
``/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:descriptiveKeywords/pass:[*]/gmd:keyword/gmx:Anchor/text()``
arvona,
ja sen URI-tunnus attribuutin
``/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:descriptiveKeywords/pass:[*]/gmd:keyword/gmx:Anchor/@xlink:href``
arvona.
|===

[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{counter:req}* {set:cellbgcolor:#CACCCE}| `vaatimus/luokka-pta-aineisto/vaatimus-asiasanasto-ankkuri` +
{set:cellbgcolor:#FFFFFF}
Metatietokuvauksessa avainsanojen sanastot on ilmaistava sekä
sanaston otsikon sisältävänä tekstinä että tai sanaston URI-tunnuksena,
mikäli yleisesti tunnettu, pysyvä URI-tunnus ko. sanastolle on olemassa.

Mikäli sanaston URI-tunnus on käytettävissä yllämainituin ehdoin, tulee sen tekstimuotoinen otsikko
ilmaista elementin
`/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:descriptiveKeywords/pass:[*]/gmd:thesaurusName/pass:[*]
/gmd:title/gmx:Anchor/]/text()`
arvona,
ja sen URI-tunnus attribuutin
`/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:descriptiveKeywords/pass:[*]/gmd:thesaurusName/pass:[*]
/gmd:title/gmx:Anchor/@xlink:href`
arvona.
|===


[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{counter:req}* {set:cellbgcolor:#CACCCE}| ``vaatimus/luokka-pta-aineisto/vaatimus-pta-asiasanat`` +
{set:cellbgcolor:#FFFFFF}
Kaikki Paikkatietohakemiston hakusanastoon sisältyvät avainsanat on määriteltävä
elementeissä, jotka löytyvät XPath-kyselyn
`/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:descriptiveKeywords
[./pass:[*]/gmd:thesaurusName/pass:[*]/gmd:title/gmx:Anchor/@xlink:href='http://paikkatiedot.fi/def/1001001/']
/pass:[*]/gmd:keyword/gmx:Anchor`
tuloksena, vaatimuksen 3 mukaisesti.
|===

==== Aineiston saatavuuden ja käytön rajoitteet

INSPIRE-metatietovaatimusten mukaan aineistojen julkinen saatavuus ja käytön rajoitteet ilmaistaan erillisinä
metatietoelementteinä (<<TG_MD_20>>, luku 2.3.6 "Limitations on public access" ja
luku 2.3.7 "Conditions applying to access and use").

TG Requirement C.17 vaatii, että
rajoitukset aineistojen julkiselle saatavuudelle tulee esittää XPath-kyselyn
`/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:resourceConstraints/pass:[*][./gmd:accessConstraints/pass:[*]/@codeListValue='otherRestrictions']/gmd:otherConstraints`
palauttamissa elementeissä. Mikäli rajoituksia ei ole tai ne eivät ole tiedossa, tulee tämä ilmaista erityisen
tähän tarkoitukseen määritellyn INSPIRE-koodilistan avulla.
PTA-aineistojen julkiseen saatavuuteen liittyen ei vaadita INSPIRE-vaatimukset ylittäviä metatietoja.

TG Requirement C.18 puolestaan vaatii, että rajoitukset aineistojen käytölle tulee joko esittää
jomman kumman seuraavista XPath-kyselyistä palauttamissa elementeissä:

1. `/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:resourceConstraints/pass:[*][./gmd:accessConstraints/pass:[*]/@codeListValue='otherRestrictions']/gmd:otherConstraints`
tai
2. `/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:resourceConstraints/pass:[*][./gmd:useConstraints/pass:[*]/@codeListValue='otherRestrictions']/gmd:otherConstraints`

Mikäli rajoituksia ei ole tai ne eivät ole tiedossa, tulee tämä ilmaista erityisen
tähän tarkoitukseen määritellyn INSPIRE-koodilistan avulla.

Lisäksi <<TG_MD_20>>:ssa vaaditaan, että vaatimusten C.17 ja C.18 kuvaamia rajoitustietoja ei saa
ilmaista saman `gmd:resourceConstraints`-elemementin avulla.

PTA-aineistojen suhteen INSPIRE-vaatimusta C.18
tiukennetaan siten, että `gmd:useConstraints`-elementtiä tulee aina käyttää aineiston käyttöön liittyvien
lisenssiehtojen tai muiden sopimusteknisten rajoittavien vaatimusten ilmaisemiseen (vaihtoehto 2 yllä).

[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{counter:req}* {set:cellbgcolor:#CACCCE}| `vaatimus/luokka-pta-aineisto/vaatimus-kayton-rajoitukset` +
{set:cellbgcolor:#FFFFFF}
Rajoitukset aineistojen käytölle, kuten vaadittavat lisenssiehdot tai muut sopimustekniset vaatimukset,
tulee esittää XPath-kyselyn
`/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:resourceConstraints/pass:[*][./gmd:useConstraints/pass:[*]/@codeListValue='otherRestrictions']/gmd:otherConstraints`
palauttamien elementtien avulla.

PTA-aineistojen lisenssiehtoja tai muita sopimusteknisiä vaatimuksia ei saa esittää XPath-kyselyn
`/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:resourceConstraints/pass:[*]/gmd:useLimitation`
palauttamien elementtien avulla. `gmd:useLimitation`-elementti on varattu aineiston soveltuvuuden rajoittamiseen
sen hyödyntämiseen tietyissä käyttötapauksissa tai sovellusalueilla.
|===

=== Jakelutiedot (distributionInfo)

Alla on listattu täydellisyyden vuoksi jakelutietoihin
liittyvät INSPIRE-vaatimukset. Näiden vaatimusten tarkemmat kuvaukset löytyvät
dokumentista <<TG_MD_20>>.

[cols="1,4",width="90%"]
|===
|*Numero* {set:cellbgcolor:#CACCCE}| *Tunnus*
|TG{nbsp}Requirement{nbsp}1.8 {set:cellbgcolor:#FFFFFF}| http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/resource-locator
|TG{nbsp}Requirement{nbsp}2.6 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/isdss/data-encoding
|===

==== Aineiston latausosoitteet
INSPIRE-vaatimus TG Requirement 1.8 vaatii antamaan URL-osoitteen josta aineiston saa ladattua, tai mikäli aineiston
lataus ei ole suoraan mahdollista, URL-osoitteen, jossa on aineistoa kuvaavaa lisätietoa, mikäli tällainen osoite on
olemassa. PTA-aineistot ovat aina saatavilla vähintään Paikkatietoalustan latauspalvelun kautta INSPIRE-yhteensopivan
rajapintapalvelun kautta, joten tätä vaatimusta voidaan tiukentaa siten, että aineiston metatieto sisältää
aina vähintään ko. aineiston PTA-latauspalveluun viittaavan suoran osoitteen.

[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{counter:req}* {set:cellbgcolor:#CACCCE}| `vaatimus/luokka-pta-aineisto/vaatimus-latauspalvelu-linkki` +
{set:cellbgcolor:#FFFFFF}

Linkit rajapintapalveluihin, joista aineisto on ladattavissa, tulee antaa aineiston metatiedoissa.
XPath-kyselyn
`/pass:[*]/gmd:distrubutionInfo[1]/pass:[*]/gmd:transferOptions/pass:[*]/gmd:online/pass:[*]/[./gmd:protocol/gmx:Anchor/@xlink:href='<protokollatunnus>']`
tulee palauttaa ko. aineiston lataamiseen tarvittavat tiedot. Merkkijonon `<protokollatunnus>` arvo määräytyy
latauspalvelun tyypin perusteella taulukon 1 mukaisesti.

Vähintään yksi tämän vaatimuksen mukainen metatietoelementti on annettava kullekin aineistolle.
|===

[#taulukko-download-protocol]
.Latauspalvelukohtaiset protokollatunnukset
|===
|*Latauspalvelun tyyppi* | *Protokollatunnus*
|INSPIRE Pre-defined Dataset WFS 2.0 | http://inspire.ec.europa.eu/id/ats/download-service/3.1/predefined-wfs
|INSPIRE Direct Access WFS 2.0 | http://inspire.ec.europa.eu/id/ats/download-service/3.1/direct-wfs
|INSPIRE Pre-defined Dataset Atom | http://inspire.ec.europa.eu/id/ats/download-service/3.1/predefined-atom
|INSPIRE WCS 2.0 Mandatory Download Operations | http://inspire.ec.europa.eu/id/ats/download-service-wcs/1.0/wcs-man
|INSPIRE WCS 2.0 Direct Access Download Operations | http://inspire.ec.europa.eu/id/ats/download-service-wcs/1.0/wcs-con
|INSPIRE Pre-defined Dataset SOS 2.0 | http://inspire.ec.europa.eu/id/ats/download-service-sos/1.0/predefined-sos
|INSPIRE Direct Access SOS 2.0 | http://inspire.ec.europa.eu/id/ats/download-service-sos/1.0/direct-sos
|===

==== Aineiston siirto- tai tallennusmuoto
INSPIRE-vaatimus TG Requirement 2.6 vaatii kuvaamaan metatiedossa ne siirto- tai tallennusmuodot (formaatit),
joiden mukaisesti koodattuna aineisto on ladattavissa. PTA-aineistoille ei aseteta erityisiä vaatimuksia
tämän INSPIRE-vaatimuksen lisäksi.

=== Laatutiedot (dataQualityInfo)
Alla on listattu täydellisyyden vuoksi laatutietoihin
liittyvät INSPIRE-vaatimukset. Näiden vaatimusten tarkemmat kuvaukset löytyvät
dokumentista <<TG_MD_20>>.

[cols="1,4",width="90%"]
|===
|*Numero* {set:cellbgcolor:#CACCCE}| *Tunnus*
|TG{nbsp}Requirement{nbsp}C.20 {set:cellbgcolor:#FFFFFF}| http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/conformity
|TG{nbsp}Requirement{nbsp}C.21 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/conformity-specification
|TG{nbsp}Requirement{nbsp}C.22 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/conformity-degree
|TG{nbsp}Requirement{nbsp}1.9 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/one-data-quality-element
|TG{nbsp}Requirement{nbsp}1.10 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/conformity
|TG{nbsp}Requirement{nbsp}1.11 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/lineage
|TG{nbsp}Requirement{nbsp}2.7 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/isdss/topological-consistency-quantitative-results
|TG{nbsp}Requirement{nbsp}2.8 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/isdss/topological-consistency-descriptive-results
|===

[#rec-lod]
[width="90%",cols="2,6"]
|===
|*Suositus{nbsp}{counter:rec}* {set:cellbgcolor:#CACCCE}| `vaatimus/luokka-pta-aineisto/suositus-yksityiskohtaisuus-luokittelu` +
{set:cellbgcolor:#FFFFFF}
Mikäli aineiston yksityiskohtaisuuden kuvaamiseen on käytettävissä yleisesti käytetty luokittelu
tai koodilista, on suositeltavaa ilmaista kuvattavan aineiston yksityiskohtaisuuden taso
 vaatimuksenmukaisuusviittauksella ko. luokitteluun laatutietoelementin alla:
 `/pass:[*]/gmd:dataQualityInfo/pass:[*]/gmd:report/gmd:DQ_DomainConsistency/gmd:result/gmd:DQ_ConformanceResult`
|===
