:Title: Paikkatietoalusta - metatietoprofiili
:titletext: Paikkatietoalusta - metatietoprofiili
:doctype: book
:encoding: utf-8
:lang: fi
:toc: macro
//:toc-placement!:
:toclevels: 3
:numbered:
:sectanchors:
:source-highlighter: pygments
:pygments-style: borland
:imagesdir: images
:appendix-caption: Liitteet
:appendix-refsig: {appendix-caption}
:caution-caption: Varoitus
:chapter-label: Luku
//:chapter-refsig: {chapter-label}
:example-caption: Esimerkki
:figure-caption: Kuvio
:important-caption: Tärkeää
:last-update-label: Viimeksi päivitetty
ifdef::listing-caption[:listing-caption: Listaus]
//:manname-title: NIMI
:note-caption: Huomautus
//:part-refsig: ???
ifdef::preface-title[:preface-title: Esipuhe]
//:section-refsig: ???
:tip-caption: Vinkki
:toc-title: Sisällysluettelo
:untitled-label: Nimetön
:version-label: Versio
:warning-caption: Ongelma
:table-caption: Taulukko
:x-versio: 1.0
:x-vaatimus-metatiedon-kieli-nro: 1
:x-vaatimus-metatiedon-tunnus-nro: 2
:x-vaatimus-tm35fin-tunnus-nro: 3
:x-vaatimus-aineiston-tunnus-nro: 4
:x-vaatimus-paivitystiheys-nro: 5
:x-vaatimus-viimeinen-paivitys-nro: 6
:x-vaatimus-asiasana-ankkuri-nro: 7
:x-vaatimus-asiasanasto-ankkuri-nro: 8
:x-vaatimus-pta-asiasanat-nro: 9
:x-vaatimus-kayton-rajoitukset-nro: 10
:x-vaatimus-latauspalvelu-linkki-nro: 11
:x-vaatimus-latauspalvelu-linkki-predefined-wfs-nro: 12
:x-vaatimus-latauspalvelu-linkki-predefined-atom-nro: 13
:x-vaatimus-latauspalvelu-linkki-wcs-nro: 14
:x-vaatimus-latauspalvelu-linkki-sos-nro: 15
:x-vaatimus-pta-vaatimuksenmukaisuus-nro: 16
:x-suositus-aineiston-pta-tunnus-nro: 1
:x-suositus-aikaviite-nro: 2
:x-suositus-maantieteellinen-kattavuus-nimi-nro: 3
:x-suositus-yksityiskohtaisuus-luokittelu-nro: 4

= {title}

<<<
[cols = "<",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Paikkatietoalusta / Maanmittauslaitos*
|Ensimmäinen versio: PTA-metatietoprofiili-projektiryhmä, toimittanut Ilkka Rinne / Spatineo Oy 2018
|Hyväksytty: pp.kk.vvvv
|Julkaistu: pp.kk.vvvv
|Dokumentin tunniste: http://paikkatiedot.fi/def/pta-metatietoprofiili/{x-versio}
|Versio: {x-versio}
|Kieli: suomi
|===

include::front_material.adoc[]

<<<
toc::[]
<<<

== Soveltamisala
Tätä ohjeistusta sovelletaan PTA-aineistojen <<ISO_19139>>-standardin mukaisten
metatietokuvausten laatimiseen, validointiin ja esittämiseen hakupalveluissa.

== Vaatimuksenmukaisuus
Tämä dokumentti määrittelee yhden vaatimuksenmukaisuusluokan '<<#luokka-pta-aineisto,PTA-aineisto>>',
jonka kohteena on <<ISO_19139>>-standardin mukainen metatietodokumentti.
Kaikkien PTA-aineistoja kuvaavien metatietodokumenttien tulee täyttää tämän
vaatimuksenmukaisuusluokan kaikki vaatimukset.

== Dokumentin konventiot

=== Tunnisteet
Tähän dokumenttiin viitataan URI-tunnuksella `http://paikkatiedot.fi/def/pta-metatietoprofiili/{x-versio}`.

Tässä dokumentissa kuvattujen vaatimusten ja suositusten kokonaisuuteen, eli vaatimuksenmukaisuusluokkaan, viitataan URI-tunnuksella
`http://paikkatiedot.fi/def/pta-metatietoprofiili/{x-versio}/vaatimukset/luokka-pta-aineisto`.

Tässä dokumentissa kuvattuihin vaatimuksille ja vaatimuksenmukaisuustesteille on annettu tekstissä osittaiset,
niin sanotut suhteelliset URI-tunnukset, joista tulee viittausta varten koostaa absoluuttiset URI-tunnukset
liittämällä osittaiset tunnukset koko dokumentin URI-tunnuksen perään. Esimerkiksi Vaatimukseen {x-vaatimus-metatiedon-kieli-nro}
viittauskelpoinen URI-tunnus on `http://paikkatiedot.fi/def/pta-metatietoprofiili/{x-versio}/vaatimukset/vaatimus-metatiedon-kieli`.

=== Graafiset elementit
Vaatimuksenmukaisuusluokka kuvataan tekstissä graafisesti seuravaavankaltaisella taulukolla:

[cols="1,4",width="90%"]
|===
2+|*Vaatimuksenmukaisuusluokka PTA-aineisto* {set:cellbgcolor:#9fc4e5}
2+| `http://paikkatiedot.fi/def/pta-metatietoprofiili/{x-versio}/vaatimukset/luokka-pta-aineisto` {set:cellbgcolor:#FFFFFF}
|===

Vaatimus kuvataan tekstissä graafisesti seuravaavankaltaisella taulukolla:

[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{x-vaatimus-metatiedon-kieli-nro}* {set:cellbgcolor:#e7e6c8}| `vaatimukset/vaatimus-metatiedon-kieli` +
{set:cellbgcolor:#FFFFFF}
|===

Suositus kuvataan tekstissä graafisesti seuravaavankaltaisella taulukolla:

[width="90%",cols="2,6"]
|===
|*Suositus{nbsp}{x-suositus-aineiston-pta-tunnus-nro}* | `vaatimukset/suositus-aineiston-pta-tunnus` +
|===


== Velvoittavat viittaukset
Seuraavat normatiiviset asiakirjat sisältävät vaatimuksia ja ehtoja, jotka viittausten kautta
muodostavat erottamattoman osan tämän dokumentin vaatimuksia. Päivättyjen viitteiden osalta asiakirjojen
mahdollisia kyseisen päivän jälkeen julkaistuja lisäyksiä tai korjauksia ei oteta huomioon. Päiväämättömien
viittausten osalta tarkoitetaan kyseisen asiankirjan viimeisintä julkaistua versiota.

<<ISO_19115>> EN ISO 19115: 2005, Geographic information - Metadata

<<ISO_19139>> ISO/TS 19139: 2007, Geographic information - Metadata - XML schema implementation

<<ISO_19105>> EN ISO 19105:2005, Geographic Information – Conformance and testing

<<ISO_639-2>> ISO 639-2:1998, Codes for the representation of names of languages – Part 2: Alpha-3 code

<<INSPIRE>> Directive 2007/2/EC of the European Parliament and of the Council of 14 March
2007 establishing an Infrastructure for Spatial Information in the European Community (INSPIRE)

<<IR_Metadata>> Commission Regulation (EC) No 1205/2008 of 3 December 2008
implementing Directive 2007/2/EC of the European Parliament and of the Council as regards
metadata.

<<IR-ISDSS>> Commission Regulation (EU) No 1089/2010 of 23 November 2010
implementing Directive 2007/2/EC of the European Parliament and of the Council as regards
interoperability of spatial data sets and services, as amended by

* Commission Regulation (EU) No 102/2011 of 4 February 2011 amending Regulation (EU) No
1089/2010 implementing Directive 2007/2/EC of the European Parliament and of the Council
as regards interoperability of spatial data sets and services;
* Commission Regulation (EU) No 1253/2013 of 21 October 2013 amending Regulation (EU)
No 1089/2010 implementing Directive 2007/2/EC as regards interoperability of spatial data
sets and services; and
* Commission Regulation (EU) No 1312/2014 of 10 December 2014 amending Regulation (EU)
No 1089/2010 implementing Directive 2007/2/EC of the European Parliament and of the
Council as regards interoperability of spatial data services.

<<TG_MD_20>> Technical Guidance for the implementation of INSPIRE dataset and service metadata based on ISO/TS 19139:2007, version 2.0, https://inspire.ec.europa.eu/id/document/tg/metadata-iso19139

<<JHS_158>> JHS 158 Paikkatietoaineistojen ja -palveluiden metatiedot, vuoden 2018 versio, http://www.jhs-suositukset.fi/suomi/jhs158

== Termit ja määritelmät
Tämän dokumentin puitteissä seuraavat termit ja määritelmät ovat voimassa:

[glossary]
Metatietoelementti:: Metatietokuvauksen yksittäinen tietoelementti tai sitä vastaava
metatietokoodauksen osa (esim. XML-elementti).
Paikkatietoinfrastruktuuri:: Paikkatietoinfrastruktuurilla tarkoitetaan tässä Inspire-direktiivin mukaista kansallista paikkatietoinfrastruktuuria kuitenkin ilman direktiivin liitteissä määriteltyjä, paikkatietoaineistojen sisällöllisiä rajauksia.
Paikkatietoalusta (PTA):: Paikkatietoalustalla tarkoitetaan tässä paikkatietoinfrastruktuuriin kuuluvaa tukipalvelua, joka mahdollistaa paikkatietoaineistojen ja -palvelujen kokoamisen ja käyttämisen yhteentoimivana kokonaisuutena.
Paikkatietoalustan ekosysteemi:: Paikkatietoalustan ekosysteemillä tarkoitetaan tässä Paikkatietoalustan kehittämisen ja käytön foorumia ja verkostoa, jossa paikkatiedon tuottajien tietoekosysteemit ja paikkatiedon hyödyntäjät sekä palveluyritykset toimivat synergisessä yhteistyössä.
Tietoekosysteemi:: Tietoekosysteemillä tarkoitetaan tässä paikkatiedon tuottajien klustereita, jotka asettavat tuottamansa paikkatiedon Paikkatietoalustan kautta yhteisen tietomallin mukaan. Ensivaiheessa Paikkatietoalustan tietoekosysteemejä ovat kansallinen maastotietokanta (KMTK) -ohjelma, kansallinen satelliittikuvien prosessointi- ja jakelupalvelu sekä valtakunnallinen osoitetietojärjestelmä -hanke.
Tuoteomistaja:: Tuoteomistajalla tarkoitetaan tässä Paikkatietoekosysteemin toimijaa, joka huolehtii Paikkatietoalustan käytännön kehitys- ja ylläpitotyöstä sekä alustapalveluista. Tuoteomistajan toiminnan tavoitteena on, että kehittämishankkeet toteutuvat suunnitellusti ja että tarjotut palvelut toimivat luotettavasti ja tehokkaasti. Tuoteomistajana toimii Maanmittauslaitos.
Tiedon tuottaja:: Tiedon tuottajalla tarkoitetaan tässä tietoekosysteemiin kuuluvaa paikkatietoa tuottavaa toimijaa, joka asettaa tiedon saataville Paikkatietoalustan kautta yhteisen tietomallin mukaan.
PTA-aineisto:: Nimetty tietoaineisto, joka on tietoekosysteemin edustajien,
tuoteomistajan ja tiedon tuottajan kesken yhteisesti tunnistettu tärkeäksi osaksi Paikkatietoalustan tietoaineistokokonaisuutta, ja jonka tuottamisesta ja käytöstä
osana Paikkatietoalustaa on yhteisesti sovittu.
Vaatimuksenmukaisuusluokka (conformance class):: Tietyn laatuvaatimustason
täyttymiseksi vaadittavien vaatimusten joukko.
Abstrakti testisarja (abstract test suite):: Abstrakti testausmoduuli, jossa
on määritelty kaikki nimetyn laatuvaatimustason täyttymiseen edellytettävät vaatimukset.
PTA-laatuvahti:: Paikkatietoalustan sisältämä aineistojen validointipalvelu.
rajapintapalvelu:: Palvelu, joka tarjotaan sovelluksen avulla tietokoneverkon kautta muiden sovellusten saataville
(<<GI_sanasto>>)
Paikkatietojatkumo (coverage):: Alueen kattavana pintana esitetty paikkatieto (<<GI_sanasto>>)
Jatkumotunnus (coverage identifier):: <<WCS_20>>-standardin mukainen yksittäisen ladattavaksi asetetun paikkatietojatkumon tunniste, joka on
yksilöivä ko. palvelun sisällä.
INSPIRE-tunnus (INSPIRE identifier):: INSPIRE-aineiston yksilöivä tunnus.
Havaintotarjoomatunnus (observation offering identifier):: <<SOS_20>>-standardin mukainen yksittäisen latattavaksi asetetun
havaintoaineiston tunnus, joka on yksilöivä ko. palvelun sisällä.
XPath-kysely:: W3C:n <<XPath_20>>-suosituksen mukainen ilmaus, jonka avulla voidaan
tehdä tarkka sisältökysely rakenteiseen XML-dokumenttiin.
URI-tunnus:: IETF:n <<URI>>-standardin mukainen resurssin tunnus.
URL-osoite:: Uniform Resource Locator, ns. web-osoite, jonka tarkoitus on osoittaa tietoverkon kautta saataville asetettuun
resurssiin. <<URL>>-osoite on URI-tunnuksen erikoistapaus.

include::johdanto.adoc[]

include::pta_aineisto.adoc[]

include::annex_a_ATS.adoc[]
<<<

////
Revision History should be the last annex before the Bibliography
Bibliography should be the last annex
////
include::annex_historia.adoc[]

<<<
include::annex_kirjallisuus.adoc[]
