== Vaatimuksenmukaisuusluokka PTA-aineisto
Paikkatietoalusta-tietoaineistojen metatietojen tulee olla kuvattu seuraavien dokumenttien tai niiden osien
sisältämien vaatimusten mukaisesti:

* 'Technical Guidance for the implementation of INSPIRE dataset and service metadata based on ISO/TS 19139:2007', vaatimustenmukaisuusluokka 'Conformance Class 2: metadata/2.0/isdss' <<TG_MD_20>>
* 'JHS 158 Paikkatietoaineistojen ja -palveluiden metatiedot', JHS-metatietoprofiili <<JHS_158>>

Lisäksi PTA-aineistojen metatietojen kuvaamisessa tulee noudattaa tässä luvussa kuvattuja PTA-kohtaisia
lisävaatimuksia.

Tämä vaatimuksenmukaisuusluokka koskee Paikkatietoalusta-palvelun keskeisiä tietoaineistoja, eli
niin sanottuja PTA-aineistoja. Palvelujen metatiedot on rajattu tämän vaatimuksenmukaisuusluokan ulkopuolelle.

[#luokka-pta-aineisto]
.Yhteenveto PTA-metatietoprofiilin sisältämistä vaatimuksista
[cols="1,4",width="90%"]
|===
2+|*Vaatimuksenmukaisuusluokka PTA-aineisto* {set:cellbgcolor:#9fc4e5}
2+| `http://paikkatietoalusta.fi/id/dok/pta-metatietoprofiili/{versio}/vaatimukset/luokka-pta-aineisto` {set:cellbgcolor:#FFFFFF}
|*Kohde* |ISO 19139 -standardin mukainen metatietodokumentti
|*Riippuvuus* |http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/isdss
|*Riippuvuus* |http://www.jhs-suositukset.fi/suomi/jhs158/jhs-metatietoprofiili
|*Vaatimus{nbsp}{x-vaatimus-metatiedon-kieli-nro}*  | `<<#vaatimus-metatiedon-kieli,vaatimukset/vaatimus-metatiedon-kieli>>` +
Metatiedon kieli on annettava ja monikielinen metatieto on koodattava käyttäen PT_FreeText-elementtejä.
|*Vaatimus{nbsp}{x-vaatimus-metatiedon-tunnus-nro}*  | `<<#vaatimus-metatiedon-tunnus,vaatimukset/vaatimus-metatiedon-tunnus>>` +
Metatietodokumentille on annettava yksilöivä UUID-muotoinen tunnus.
|*Vaatimus{nbsp}{x-vaatimus-tm35fin-tunnus-nro}*  | `<<#vaatimus-tm35fin-tunnus,vaatimukset/vaatimus-tm35fin-tunnus>>` +
ETRS-TM35FIN-järjestelmän mukainen koodinaatisto tulee esittää URI-tunnusta käyttäen.
|*Vaatimus{nbsp}{x-vaatimus-aineiston-tunnus-nro}*  | `<<#vaatimus-aineiston-tunnus,vaatimukset/vaatimus-aineiston-tunnus>>` +
Aineistolle on annettava yksilöivä, pysyvä URL-muotoinen tunnus.
|*Vaatimus{nbsp}{x-vaatimus-paivitystiheys-nro}*  | `<<#vaatimus-paivitystiheys,vaatimukset/vaatimus-paivitystiheys>>` +
Aineiston säännöllinen päivitystiheys on annettava, mikäli se on määritelty.
|*Vaatimus{nbsp}{x-vaatimus-viimeinen-paivitys-nro}*  | `<<#vaatimus-viimeinen-paivitys,vaatimukset/vaatimus-viimeinen-paivitys>>` +
Aineiston viimeisin päivitysajankohta on annettava, mikäli päivitystiheyttä ei ole annettu.
|*Vaatimus{nbsp}{x-vaatimus-asiasana-ankkuri-nro}*  | `<<#vaatimus-asiasana-ankkuri,vaatimukset/vaatimus-asiasana-ankkuri>>` +
Avainsanojen URI-tunnukset on annettava, mikäli ne ovat tiedossa.
|*Vaatimus{nbsp}{x-vaatimus-asiasanasto-ankkuri-nro}*  | `<<#vaatimus-asiasanasto-ankkuri,vaatimukset/vaatimus-asiasanasto-ankkuri>>` +
Avainsanastojen URI-tunnukset on annettava, mikäli ne ovat tiedossa.
|*Vaatimus{nbsp}{x-vaatimus-pta-asiasanat-nro}*  | `<<#vaatimus-pta-asiasanat,vaatimukset/vaatimus-pta-asiasanat>>` +
Vähintään yksi asiasana Paikkatietohakemiston hakusanastosta on annettava.
|*Vaatimus{nbsp}{x-vaatimus-kayton-rajoitukset-nro}*  | `<<#vaatimus-kayton-rajoitukset,vaatimukset/vaatimus-kayton-rajoitukset>>` +
Sopimustekniset rajoitukset aineistojen käytölle on annettava useConstraints-elementin avulla.
|*Vaatimus{nbsp}{x-vaatimus-latauspalvelu-linkki-nro}*  | `<<#vaatimus-latauspalvelu-linkki,vaatimukset/vaatimus-latauspalvelu-linkki>>` +
Vähintään yksi linkki aineistoa tarjoavaan rajapintapalveluun on annettava.
|*Vaatimus{nbsp}{x-vaatimus-latauspalvelu-linkki-predefined-wfs-nro}*  | `<<#vaatimus-latauspalvelu-linkki-predefined-wfs,vaatimukset/vaatimus-latauspalvelu-linkki-predefined-wfs>>` +
Aineiston INSPIRE-tunnus on annettava INSPIRE Pre-defined WFS -palveluun linkitettäessä.
|*Vaatimus{nbsp}{x-vaatimus-latauspalvelu-linkki-predefined-atom-nro}*  | `<<#vaatimus-latauspalvelu-linkki-predefined-atom,vaatimukset/vaatimus-latauspalvelu-linkki-predefined-atom>>` +
Aineiston palvelusyötteen kuvattavan aineiston kohdan tunnus on annettava INSPIRE Pre-defined Atom -palveluun linkitettäessä.
|*Vaatimus{nbsp}{x-vaatimus-latauspalvelu-linkki-wcs-nro}*  | `<<#vaatimus-latauspalvelu-linkki-wcs,vaatimukset/vaatimus-latauspalvelu-linkki-wcs>>` +
Aineiston jatkumotunnus (coverageId) on annettava Web Coverage Service -palveluun linkitettäessä.
|*Vaatimus{nbsp}{x-vaatimus-latauspalvelu-linkki-sos-nro}*  | `<<#vaatimus-latauspalvelu-linkki-sos,vaatimukset/vaatimus-latauspalvelu-linkki-sos>>` +
Aineiston havaintotarjoomatunnus (ObservationOffering Identifier) on annettava Sensor Observation Service -palveluun linkitettäessä.
|*Vaatimus{nbsp}{x-vaatimus-pta-vaatimuksenmukaisuus-nro}*  | `<<#vaatimus-pta-vaatimuksenmukaisuus,vaatimukset/vaatimus-pta-vaatimuksenmukaisuus>>` +
Aineistolle ajettujen laaduntarkastustestien tulokset on annettava vaatimuksenmukaisuusluokkakohtaisesti.
|*Suositus{nbsp}{x-suositus-aineiston-pta-tunnus-nro}*  | `<<#suositus-aineiston-pta-tunnus,vaatimukset/suositus-aineiston-pta-tunnus>>` +
Suositellaan käytettäväksi Paikkatietoalustan aineistotunnukseen perustuvaa URI-tunnusta aineiston tunnuksena, ellei
ole erityistä tarvetta käyttää muuta tunnusta.
|*Suositus{nbsp}{x-suositus-aikaviite-nro}*  | `<<#suositus-aikaviite,vaatimukset/suositus-aikaviite>>` +
Mikäli viimeisintä päivitysajankohtaa ei anneta, suositellaan aikaviitteeksi joko aineiston ajallista kattavuutta tai sen luontiajankohtaa.
|*Suositus{nbsp}{x-suositus-yksityiskohtaisuus-luokittelu-nro}*  | `<<#suositus-yksityiskohtaisuus-luokittelu,vaatimukset/suositus-yksityiskohtaisuus-luokittelu>>` +
Aineiston yksityiskohtaisuus suositellaan kuvattavan laatutiedoissa, mikäli yksityiskohtaisuuden kuvaamiseen
on käytössä yleisesti tunnettu luokittelu.
|===

=== Yleiset metatiedon XML-koodaukseen kohdistuvat vaatimukset
Alla on listattu yleiset <<ISO_19139>>-standardin mukaisen
metatiedon koodaukseen liittyvät INSPIRE-vaatimukset. Näiden vaatimusten tarkemmat kuvaukset löytyvät
dokumentista <<TG_MD_20>>.

.Yleiset metatiedon XML-koodaukseen kohdistuvat INSPIRE-vaatimukset
[cols="1,4",width="90%"]
|===
|*Numero* {set:cellbgcolor:#e9e9e9}| *Tunnus*
|TG{nbsp}Requirement{nbsp}C.1 {set:cellbgcolor:#FFFFFF}| http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/xml-schema
|TG{nbsp}Requirement{nbsp}C.2 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/root-element
|TG{nbsp}Requirement{nbsp}C.3 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/code-list-value
|TG{nbsp}Requirement{nbsp}C.4 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/free-text
|===

PTA-aineistojen suhteen ei yllämainittujen lisäksi esitetä lisävaatimuksia.

=== Metatiedon tunnistamistiedot
Alla on listattu metatiedon tunnistamistietoihin
liittyvät INSPIRE-vaatimukset. Näiden vaatimusten tarkemmat kuvaukset löytyvät
dokumentista <<TG_MD_20>>.

.Metatiedon tunnistamistietoihin kohdistuvat INSPIRE-vaatimukset
[cols="1,4",width="90%"]
|===
|*Numero* {set:cellbgcolor:#e9e9e9}| *Tunnus*
|TG{nbsp}Requirement{nbsp}C.5 {set:cellbgcolor:#FFFFFF}| http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/metadata-language-code
|TG{nbsp}Requirement{nbsp}C.6 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/md-point-of-contact
|TG{nbsp}Requirement{nbsp}C.7 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/md-date
|TG{nbsp}Requirement{nbsp}C.19 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/bounding-box
|TG{nbsp}Requirement{nbsp}1.1 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/resource-type
|===

PTA-aineistojen suhteen esitetään lisäksi tämän luvun alilukujen sisältämät lisävaatimukset.

==== Metatiedon kieli ja monikielisyys
INSPIRE-vaatimus TG Requirement C.5 vaatii ilmaisemaan luonnollisen kielen, jolla metatiedon vapaatekstisisältö on
kuvattu. Lisäksi vaatimus TG Requirement C.4 esittää kolme sallittua vaihtoehtoa vapaateksti-arvoisten metatietoelementtien
ilmaisemiseen. PTA-aineistojen suhteen monikielisen metatietosisällön tarjoamista koskevaa INSPIRE-vaatimusta tiukennetaan
siten, että mahdolliset käännökset metatiedon kielellä ilmaistuille sisällöille esitetään aina samassa
metatietodokumentissa alkuperäisen sisällön kanssa.

[#vaatimus-metatiedon-kieli]
[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{x-vaatimus-metatiedon-kieli-nro}* {set:cellbgcolor:#e7e6c8}| `vaatimukset/vaatimus-metatiedon-kieli` +
{set:cellbgcolor:#FFFFFF}
Mikäli PTA-aineiston metatietokuvaus on saatavilla useammalla kuin yhdellä kielellä, tulee niistä yksi valita
metatiedon kieleksi INSPIRE-vaatimuksen TG Requirement C.5 mukaisesti.

XPath-kyselyn
`/pass:[*]/gmd:locale/gmd:PT_Locale[@id]`
tulee palauttaa yllä määritellyn metatiedon kielen lisäksi metatietokuvauksessa
käytettyjen kieli- ja merkistöyhdistelmien tiedot. +

Kunkin monikielisen vapaatekstielementin
tyyppi on määriteltävä uudelleen dynaamisella tyypityksellä (attribuutti `xsi:type="gmd:PT_FreeText_PropertyType"`) INSPIRE-vaatimuksen
TG Requirement C.4 vaihtoehdon 3 mukaisesti. +

XPath-kyselyn
`//gmd:PT_FreeText/gmd:textGroup/gmd:LocalisedCharacterString[@locale='#<locale_id>']/text()`
tulee palauttaa arvot niille vapaatekstikentille, jotka on annettu eri kielellä kuin
yllä määritelty metatiedon kieli. Merkkijonon `<locale_id>` arvo on oltava kyseisen kieli- ja merkistöyhdistelmän
kuvaavan elementin `/pass:[*]/gmd:locale/gmd:PT_Locale` attribuutin `id` arvo.
|===

.Esimerkki{nbsp}{counter:example}: Metatiedon kieli ja monikielinen otsikko
[source,xml]
----
<gmd:language>
  <gmd:LanguageCode codeList="http://www.loc.gov/standards/iso639-2/" codeListValue="fin">Finnish</gmd:LanguageCode>
</gmd:language>
...
<gmd:locale>
  <gmd:PT_Locale id="lang-se">
     <gmd:languageCode>
        <gmd:LanguageCode
           codeList="http://www.loc.gov/standards/iso639-2"
           codeListValue="swe">Swedish</gmd:LanguageCode>
     </gmd:languageCode>
     <gmd:characterEncoding>
        <gmd:MD_CharacterSetCode
           codeList="http://standards.iso.org/iso/19139/resources/
           gmxCodelists.xml#MD_CharacterSetCode"
           codeListValue="utf8">UTF-8</gmd:MD_CharacterSetCode>
     </gmd:characterEncoding>
  </gmd:PT_Locale>
</gmd:locale>
...
      <gmd:CI_Citation>
         <gmd:title xsi:type="gmd:PT_FreeText_PropertyType">
            <gco:CharacterString>Johdot ja kaapelit</gco:CharacterString>
            <gmd:PT_FreeText>
               <gmd:textGroup>
                  <gmd:LocalisedCharacterString locale="#lang-se">Ledningar och kablar</gmd:LocalisedCharacterString>
               </gmd:textGroup>
            </gmd:PT_FreeText>
         </gmd:title>
----

==== Metatietokuvauksen yksilöivä tunnus

<<TG_MD_20>> suosittelee pysyvien ja globaalisti yksilöivien tunnusten antamista INSPIRE-aineistojen metatietokuvauksille käyttäen elementtiä
`gmd:fileIdentifier`.

[#vaatimus-metatiedon-tunnus]
[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{x-vaatimus-metatiedon-tunnus-nro}* {set:cellbgcolor:#e7e6c8}| `vaatimukset/vaatimus-metatiedon-tunnus` +
{set:cellbgcolor:#FFFFFF}
PTA-aineistojen <<ISO_19139, ISO 19139>> -muotoisissa metatietokuvauksille on annettava globaalisti
yksilöivä merkkijonomuotoinen UUID-tunnus. XPath-kyselyn
`/pass:[*]/gmd:fileIdentifier/text()`
tulee palauttaa näin määritelty metatiedon yksilöivä tunnus.
|===

=== Vertausjärjestelmä (referenceSystemInfo)

Alla on listattu vertausjärjestelmään
liittyvät INSPIRE-vaatimukset. Näiden vaatimusten tarkemmat kuvaukset löytyvät
dokumentista <<TG_MD_20>>.

.Vertausjärjestelmien kuvaamiseen kohdistuvat INSPIRE-vaatimukset
[cols="1,4",width="90%"]
|===
|*Numero* {set:cellbgcolor:#e9e9e9}| *Tunnus*
|TG{nbsp}Requirement{nbsp}2.1 {set:cellbgcolor:#FFFFFF}| http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/isdss/crs
|TG{nbsp}Requirement{nbsp}2.2 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/isdss/crs-id
|TG{nbsp}Requirement{nbsp}2.3 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/isdss/temportal-rs
|===

<<TG_MD_20>>:n vaatimus TG Requirement 2.2 vaatii, että vertausjärjestelmätunnuksina käytetään
kyseisen asiakirjan Annex D.4:n sisältämän taulukon "Default Coordinate Reference Systems"
URI-muotoisia tunnuksia, mikäli aineiston vertausjärjestelmä on lueteltu kyseisessä taulukossa.

Suomessa on yleisesti käytössä spatiaalinen vertausjärjestelmä ETRS-TM35FIN, joka on <<JHS_197>>:n mukainen
suositeltu tasokoortinaattijärjestelmä koko Suomen alueen kattaville aineistoille. ETRS-TM35FIN-järjestelmän
mukaiset koordinaatistot eivät sisälly <<TG_MD_20>>:n Annex D.4:n taulukkoon.

[#vaatimus-tm35fin-tunnus]
[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{x-vaatimus-tm35fin-tunnus-nro}* {set:cellbgcolor:#e7e6c8}| `vaatimukset/vaatimus-tm35fin-tunnus` +
{set:cellbgcolor:#FFFFFF}
Mikäli aineistossa käytetty spatiaalinen vertausjärjestelmä on ETRS-TM35FIN, tulee se ilmaista
metatiedossa käyttäen jompaa kumpaa taulukon 5 HTTP URI -muotoisista tunnuksista, riippuen käytetystä
koodinaattijärjestyksestä (N,E) tai (E,N).

XPath-kyselyn +
`/pass:[*]/gmd:referenceSystemInfo/pass:[*]/gmd:referenceSystemIdentifier/gmd:RS_Identifier/gmd:code +
/gmx:Anchor/@xlink:href`
tulee palauttaa käytetyn ETRS-TM35FIN-koordinaatiston URI-tunnus.
|===

[#taulukko-tm35fin-uris]
.ETRS-TM35FIN-järjestelmän mukaisten koordinaatistojen URI-tunnukset
[width="90%",cols="2,6"]
|===
|*Nimi* {set:cellbgcolor:#e9e9e9} | *HTTP URI -tunnus*
|ETRS89 / TM35FIN (E,N) {set:cellbgcolor:#FFFFFF} | http://www.opengis.net/def/crs/EPSG/0/3067
|ETRS89 / TM35FIN (N,E) | http://www.opengis.net/def/crs/EPSG/0/5048
|===

=== Resurssin tunnistamistiedot (indentificationInfo)

Alla on listattu resurssin tunnistamistietoihin
liittyvät INSPIRE-vaatimukset. Näiden vaatimusten tarkemmat kuvaukset löytyvät
dokumentista <<TG_MD_20>>.

.Resurssin tunnistamistietoihin kohdistuvat INSPIRE-vaatimukset
[cols="1,4",width="90%"]
|===
|*Numero* {set:cellbgcolor:#e9e9e9}| *Tunnus*
|TG{nbsp}Requirement{nbsp}C.8 {set:cellbgcolor:#FFFFFF}|http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/resource-title
|TG{nbsp}Requirement{nbsp}C.9 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/resource-abstract
|TG{nbsp}Requirement{nbsp}C.10 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/responsible-organisation
|TG{nbsp}Requirement{nbsp}C.11 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/temporal-reference
|TG{nbsp}Requirement{nbsp}C.12 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/max-1-date-of-creation
|TG{nbsp}Requirement{nbsp}C.13 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/max-1-date-of-last-revision
|TG{nbsp}Requirement{nbsp}C.14 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/metadata/2.0/req/common/temporal-extent
|TG{nbsp}Requirement{nbsp}C.15 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/metadata/2.0/req/common/keyword-originating-cv
|TG{nbsp}Requirement{nbsp}C.16 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/metadata/2.0/req/common/group-keywords-by-cv
|TG{nbsp}Requirement{nbsp}C.17 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/metadata/2.0/req/common/limitations-on-public-access
|TG{nbsp}Requirement{nbsp}C.18 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/metadata/2.0/req/common/conditions-for-access-and-use
|TG{nbsp}Requirement{nbsp}1.2 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/only-one-md-data-identification
|TG{nbsp}Requirement{nbsp}1.3 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/dataset-uid
|TG{nbsp}Requirement{nbsp}1.4 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/inspire-theme-keyword
|TG{nbsp}Requirement{nbsp}1.5 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/spatial-resolution
|TG{nbsp}Requirement{nbsp}1.6 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/resource-language
|TG{nbsp}Requirement{nbsp}1.7 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/topic-category
|TG{nbsp}Requirement{nbsp}2.4 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/isdss/spatial-representation-type
|TG{nbsp}Requirement{nbsp}2.5 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/isdss/character-encoding
|===

PTA-aineistojen suhteen esitetään lisäksi tämän luvun alilukujen sisältämät lisävaatimukset.

==== Aineiston yksilöivä tunnus

INSPIRE-aineistoille on annettava yksilöivä URI-muotoinen tunnus (<<TG_MD_20>>, TG Requirement 1.3). Lisäksi
suositellaan, että aineiston tunnus on pysyvä (TG Recommendation 1.3), että käytettävä URI-tunnus on
HTTP- tai HTTPS-protokollan mukainen URL-osoite (TG Recommendation 1.2), ja että aineiston tunnus tulisi
ilmaista käyttäen `gmd:MD_Identifier`-elementtiä (TG Recommendation 1.1).

[#vaatimus-aineiston-tunnus]
[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{x-vaatimus-aineiston-tunnus-nro}* {set:cellbgcolor:#e7e6c8}| `vaatimukset/vaatimus-aineiston-tunnus` +
{set:cellbgcolor:#FFFFFF}
PTA-aineistolle tulee antaa pysyvä URL-muotoinen tunnus. URL-osoitteen protokollan tulee olla joko `HTTP` tai `HTTPS`,
ja sen tulee osoittaa ko. protokollan mukaisesti joko suoraan tai uudelleenohjauksen avulla julkisessa Internetissä sijaitsevaan dokumentiin, joka antaa
lisätietoja kuvatusta aineistosta. Palautettava dokumentti voi olla, mutta sen ei tarvitse olla aineiston
metatietokuvaus.

XPath-kyselyn +
`/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:citation/pass:[*]/gmd:identifier/gmd:MD_Identifier/gmd:code/pass:[*]/text()`
tulee palauttaa aineiston URL-tunnus.
|===

[#suositus-aineiston-pta-tunnus]
[width="90%",cols="2,6"]
|===
|*Suositus{nbsp}{x-suositus-aineiston-pta-tunnus-nro}* | `vaatimukset/suositus-aineiston-pta-tunnus` +
Mikäli PTA-aineistolle ei Paikkatietoalustan ulkopuolella ole annettu INSPIRE-vaatimukset ja yllä kuvatun Vaatimuksen
{x-vaatimus-aineiston-tunnus-nro} ehdot täyttävää URL-muotoista tunnusta, on suositeltavaa käyttää aineiston yksilöivänä
tunnuksena Paikkatietoalustan tuottamaa, aineiston PTA-tunnukseen perustuvaa pysyvää URL-osoitetta, joka uudelleenohjataan
Paikkatietoalustan hakupalvelun kyseisen aineiston tietokorttisivulle.

Mikäli aineisto poistetaan Paikkatietoikkunasta tai se korvataan toisella
aineistolla, jolla on eri tunnus, tulisi poistetun aineiston URL-tunnuksen osoittaa sivuun, jossa kerrotaan että
ko. aineisto ei ole enää saatavilla Paikkatietoikkunan kautta.
|===

==== Aineiston aikaviitteet

[#vaatimus-paivitystiheys]
[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{x-vaatimus-paivitystiheys-nro}* {set:cellbgcolor:#e7e6c8}| `vaatimukset/vaatimus-paivitystiheys` +
{set:cellbgcolor:#FFFFFF}
Mikäli aineistolle on määritelty säännöllinen päivitystiheys, ja se voidaan ilmaista
ISO 19139 -standardin koodilistan `MD_MaintenanceFrequencyCode` arvojen avulla, on
se annettava metatiedossa. Seuraavan XPath-kyselyn tulee tällöin
palauttaa aineiston päivitystiheystieto: +
`/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:resourceMaintenance/pass:[*]
/gmd:maintenanceAndUpdateFrequency/gmd:MD_MaintenanceFrequencyCode/@codeListValue`

Koodin on oltava yksi ISO 19139 -standardin koodilistan `MD_MaintenanceFrequencyCode` sallituista arvoista.
|===

[NOTE]
====
INSPIRE <<TG_MD_20>> TG Requirement C.11:ssa vaaditaan, että aineiston aikaviite annetaan vähintään yhdellä
seuraavista tavoista:

* ajallinen kattavuus (temporal extent),
* julkaisupäivämäärä,
* viimeisin päivitysajankohta, tai
* luontiajankohta.

Siten pelkkä aineiston päivitystiheyden kuvaaminen ei riitä täyttämään INSPIRE-vaatimuksia aikaviitteiden osalta.
====

[#suositus-aikaviite]
[width="90%",cols="2,6"]
|===
|*Suositus{nbsp}{x-suositus-aikaviite-nro}* | `vaatimukset/suositus-aikaviite` +
Mikäli aineistolle on kuvattu metatiedossa päivitystiheys, eikä aineiston
viimeisintä päivitysajankohtaa ole mielekästä pitää ajantasalla, on
suositeltavaa antaa joko aineiston ajallinen kattavuus tai sen luontiajankohta.
|===

[#vaatimus-viimeinen-paivitys]
[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{x-vaatimus-viimeinen-paivitys-nro}* {set:cellbgcolor:#e7e6c8}| `vaatimukset/vaatimus-viimeinen-paivitys` +
{set:cellbgcolor:#FFFFFF}
Mikäli aineistolle ei ole metatiedossa kuvattu säännöllistä päivitystiheyttä
<<vaatimus-paivitystiheys, Vaatimuksen {x-vaatimus-paivitystiheys-nro}>> mukaisesti, on
aineiston viimeisin päivitysajankohta on annettava. Seuraavan XPath-kyselyn tulee tällöin palauttaa aineiston
viimeisin päivitysajankohta päivän tarkkudella:
`/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:citation/pass:[*]/gmd:date
[./pass:[*]/gmd:dateType/pass:[*]/@codeListValue='revision']/pass:[*]/gmd:date/gco:Date/text()`
|===

==== Sijainnillinen yksityiskohtaisuus

INSPIRE-vaatimuksen TG Requirement 1.5 mukaisesti aineiston erotyskyky on annettava, mikäli se on ko. aineistolle
saatavissa. Erotuskyky tulee tällöin antaa joko mittakaavana (equivalent scale) tai näytetiheytenä
(resolution distance).

[NOTE]
====
Mittakaava tai näytetiheys ei ole kaikista tarkoituksenmukaisin tapa ilmaista kaikkien PTA-aineiston
yksityiskohtaisuuden tasoa. Esimerkiksi rakennetun ympäristön CityGML-aineistoissa yksityiskohtaisuus
ilmaistaan CityGML-standardissa määritellyillä level of detail -tasoilla (LOD0 - LOD4) <<CityGML>>.
PTA-metatietokuvauksessa suositellaan tällaisissa tapauksissa käytettäväksi
vaatimuksenmukaisuus-viittausta osana laatutietoja (ks. <<rec-lod, Suositus 3>>)
====

==== Avainsanat

INSPIRE-suositukset TG Recommendation C.8 ja C.9 suosittelevat `gmx:Anchor`-elementin ja URI-tunnusten
käyttöä avainsanoihin ja sanastoihin viittaamisessa. PTA-aineistojen metatietokuvauksessa tämä viittaustapa
on pakollinen, mikäli yleisesti tunnettu URI-tunnus käytettyihin sanastoihin ja avainsanoihin on olemassa.

[#vaatimus-asiasana-ankkuri]
[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{x-vaatimus-asiasana-ankkuri-nro}* {set:cellbgcolor:#e7e6c8}| `vaatimukset/vaatimus-asiasana-ankkuri` +
{set:cellbgcolor:#FFFFFF}
Metatietokuvauksessa aineistoa kuvaavat avainsanat on ilmaistava sekä
itse avainsanan sisältävänä tekstinä että ko. avainsanan URI-tunnuksena,
mikäli yleisesti tunnettu, pysyvä URI-tunnus ko. asiasanalle on olemassa.

Mikäli asiasanan URI-tunnus on käytettävissä yllämainituin ehdoin, tulee tekstimuotoinen avainsana
ilmaista elementin
`/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:descriptiveKeywords/pass:[*]/gmd:keyword +
/gmx:Anchor/text()`
arvona,
ja sen URI-tunnus attribuutin
`/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:descriptiveKeywords/pass:[*]/gmd:keyword +
/gmx:Anchor/@xlink:href`
arvona.
|===

[#vaatimus-asiasanasto-ankkuri]
[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{x-vaatimus-asiasanasto-ankkuri-nro}* {set:cellbgcolor:#e7e6c8}| `vaatimukset/vaatimus-asiasanasto-ankkuri` +
{set:cellbgcolor:#FFFFFF}
Metatietokuvauksessa avainsanojen sanastot on ilmaistava sekä
sanaston otsikon sisältävänä tekstinä että tai sanaston URI-tunnuksena,
mikäli yleisesti tunnettu, pysyvä URI-tunnus ko. sanastolle on olemassa.

Mikäli sanaston URI-tunnus on käytettävissä yllämainituin ehdoin, tulee sen tekstimuotoinen otsikko
ilmaista elementin
`/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:descriptiveKeywords/pass:[*]/gmd:thesaurusName +
/pass:[*]/gmd:title/gmx:Anchor/]/text()`
arvona,
ja sen URI-tunnus attribuutin
`/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:descriptiveKeywords/pass:[*]/gmd:thesaurusName +
/pass:[*]/gmd:title/gmx:Anchor/@xlink:href`
arvona.
|===

[#vaatimus-pta-asiasanat]
[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{x-vaatimus-pta-asiasanat-nro}* {set:cellbgcolor:#e7e6c8}| `vaatimukset/vaatimus-pta-asiasanat` +
{set:cellbgcolor:#FFFFFF}
Kaikki Paikkatietohakemiston hakusanastoon sisältyvät avainsanat on määriteltävä
elementeissä, jotka löytyvät XPath-kyselyn
`/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:descriptiveKeywords +
[./pass:[*]/gmd:thesaurusName/pass:[*]/gmd:title/gmx:Anchor/@xlink:href='http://paikkatiedot.fi/def/1001001/'] +
/pass:[*]/gmd:keyword/gmx:Anchor`
tuloksena, Vaatimuksen {x-vaatimus-asiasana-ankkuri-nro} mukaisesti.

Kunkin PTA-aineiston metatietokuvauksessa on käytettävä vähintään yhtä Paikkatietohakemiston
hakusanaston avainsanaa.
|===

WARNING: Mistä Paikkatietohakemiston hakusanaston sanat ja niiden URL-osoitteet voi löytää? Fintossa ei voi tehdä hakua,
joka palauttaisi kaikki ko. sanaston sanat, vaikka vapaasanahakua voikin rajata koskemaan vain Paikkatietohakemiston hakusanastoa.

==== Aineiston saatavuuden ja käytön rajoitteet

INSPIRE-metatietovaatimusten mukaan aineistojen julkinen saatavuus ja käytön rajoitteet ilmaistaan erillisinä
metatietoelementteinä (<<TG_MD_20>>, luku 2.3.6 "Limitations on public access" ja
luku 2.3.7 "Conditions applying to access and use").

TG Requirement C.17 vaatii, että
rajoitukset aineistojen julkiselle saatavuudelle tulee esittää XPath-kyselyn
`/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:resourceConstraints/pass:[*][./gmd:accessConstraints/pass:[*]/@codeListValue='otherRestrictions']/gmd:otherConstraints`
palauttamissa elementeissä. Mikäli rajoituksia ei ole tai ne eivät ole tiedossa, tulee tämä ilmaista erityisen
tähän tarkoitukseen määritellyn INSPIRE-koodilistan avulla.
PTA-aineistojen julkiseen saatavuuteen liittyen ei vaadita INSPIRE-vaatimukset ylittäviä metatietoja.

.Esimerkki{nbsp}{counter:example}: Aineiston julkista saatavuutta rajoitettu INSPIRE-direktiin artiklan 13(1) perusteella, esimerkki suoraan <<TG_MD_20>>:sta. Esimerkissa metatiedon kieli on ranska.
[source,xml]
----
/*/gmd:identificationInfo/*/gmd:resourceConstraints:

<gmd:resourceConstraints>
  <gmd:MD_LegalConstraints>
    <gmd:accessConstraints>
      <gmd:MD_RestrictionCode
codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode"
codeListValue="otherRestrictions" />
    </gmd:accessConstraints>
    <gmd:otherConstraints>
      <gmx:Anchor
xlink:href="http://inspire.ec.europa.eu/metadatacodelist/
LimitationsOnPublicAccess/INSPIRE_Directive_Article13_1a">
Limitation d’accés public basé sur l’article 13(1) de la directive INSPIRE
      </gmx:Anchor>
    </gmd:otherConstraints>
  </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
----

TG Requirement C.18 puolestaan vaatii, että rajoitukset aineistojen käytölle tulee joko esittää
jomman kumman seuraavista XPath-kyselyistä palauttamissa elementeissä:

1. `/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:resourceConstraints/pass:[*][./gmd:accessConstraints/pass:[*]/@codeListValue='otherRestrictions']/gmd:otherConstraints`
tai
2. `/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:resourceConstraints/pass:[*][./gmd:useConstraints/pass:[*]/@codeListValue='otherRestrictions']/gmd:otherConstraints`

Mikäli rajoituksia ei ole tai ne eivät ole tiedossa, tulee tämä ilmaista erityisen
tähän tarkoitukseen määritellyn INSPIRE-koodilistan avulla.

Lisäksi <<TG_MD_20>>:ssa vaaditaan, että vaatimusten C.17 ja C.18 kuvaamia rajoitustietoja ei saa
ilmaista saman `gmd:resourceConstraints`-elemementin avulla.

PTA-aineistojen suhteen INSPIRE-vaatimusta C.18
tiukennetaan siten, että `gmd:useConstraints`-elementtiä tulee aina käyttää aineiston käyttöön liittyvien
lisenssiehtojen tai muiden sopimusteknisten rajoittavien vaatimusten ilmaisemiseen (vaihtoehto 2 yllä).

[#vaatimus-kayton-rajoitukset]
[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{x-vaatimus-kayton-rajoitukset-nro}* {set:cellbgcolor:#e7e6c8}| `vaatimukset/vaatimus-kayton-rajoitukset` +
{set:cellbgcolor:#FFFFFF}
Rajoitukset aineistojen käytölle, kuten vaadittavat lisenssiehdot tai muut sopimustekniset vaatimukset,
tulee esittää XPath-kyselyn
`/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:resourceConstraints/pass:[*][./gmd:useConstraints/pass:[*]/@codeListValue='otherRestrictions']/gmd:otherConstraints`
palauttamien elementtien avulla.

PTA-aineistojen lisenssiehtoja tai muita sopimusteknisiä vaatimuksia ei saa esittää XPath-kyselyn
`/pass:[*]/gmd:identificationInfo[1]/pass:[*]/gmd:resourceConstraints/pass:[*]/gmd:useLimitation`
palauttamien elementtien avulla. `gmd:useLimitation`-elementti on varattu aineiston soveltuvuuden rajoittamiseen
sen hyödyntämiseen tietyissä käyttötapauksissa tai sovellusalueilla.
|===

.Esimerkki{nbsp}{counter:example}: Aineisto saatavilla lisenssillä Creative Commons Nimeä 4.0 Kansainvälinen (CC BY 4.0)
[source,xml]
----
/*/gmd:identificationInfo/*/gmd:resourceConstraints:

<gmd:resourceConstraints>
   <gmd:MD_LegalConstraints>
      <gmd:useConstraints>
         <gmd:MD_RestrictionCode
            codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode"
            codeListValue="otherRestrictions" />
      </gmd:useConstraints>
      <gmd:otherConstraints>
         <gmx:Anchor
            xlink:href="https://creativecommons.org/licenses/by/4.0/deed.fi">
            Nimeä 4.0 Kansainvälinen (CC BY 4.0)
         </gmx:Anchor>
      </gmd:otherConstraints>
   </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
----

=== Jakelutiedot (distributionInfo)

Alla on listattu täydellisyyden vuoksi jakelutietoihin
liittyvät INSPIRE-vaatimukset. Näiden vaatimusten tarkemmat kuvaukset löytyvät
dokumentista <<TG_MD_20>>.

.Jakelutietoihin kohdistuvat INSPIRE-vaatimukset
[cols="1,4",width="90%"]
|===
|*Numero* {set:cellbgcolor:#e9e9e9}| *Tunnus*
|TG{nbsp}Requirement{nbsp}1.8 {set:cellbgcolor:#FFFFFF}| http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/resource-locator
|TG{nbsp}Requirement{nbsp}2.6 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/isdss/data-encoding
|===

PTA-aineistojen suhteen esitetään lisäksi tämän luvun alilukujen sisältämät lisävaatimukset.

==== Aineiston latauspalvelujen osoitteet
INSPIRE-vaatimus TG Requirement 1.8 vaatii antamaan URL-osoitteen josta aineiston saa ladattua, tai mikäli aineiston
lataus ei ole suoraan mahdollista, URL-osoitteen, jossa on aineistoa kuvaavaa lisätietoa, mikäli tällainen osoite on
olemassa. PTA-aineistot ovat aina saatavilla vähintään Paikkatietoalustan latauspalvelun kautta INSPIRE-yhteensopivan
rajapintapalvelun kautta, joten tätä vaatimusta voidaan tiukentaa siten, että aineiston metatieto sisältää
aina vähintään ko. aineiston PTA-latauspalveluun viittaavan suoran osoitteen.

[#vaatimus-latauspalvelu-linkki]
[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{x-vaatimus-latauspalvelu-linkki-nro}* {set:cellbgcolor:#e7e6c8}| `vaatimukset/vaatimus-latauspalvelu-linkki` +
{set:cellbgcolor:#FFFFFF}

Linkit rajapintapalveluihin, joista aineisto on ladattavissa, tulee antaa aineiston metatiedoissa.
XPath-kyselyn
`/pass:[*]/gmd:distrubutionInfo[1]/pass:[*]/gmd:transferOptions/pass:[*]/gmd:onLine/pass:[*][./gmd:function/gmd:CI_OnLineFunctionCode/@codeListValue='download' and ./gmd:protocol/gmx:Anchor/@xlink:href='<protokollatunnus>']/gmd:linkage/gmd:URL/text()`
tulee palauttaa URL-osoitteen rajapintapalveluun, josta metatiedossa kuvatun aineiston voi ladata joko kokonaisuudessaan
tai osittain palvelun tyypistä riippuen. Merkkijonon `<protokollatunnus>` arvo määräytyy
rajapintapalvelun tyypin perusteella taulukon 7 mukaisesti.

Vähintään yksi tämän vaatimuksen mukainen metatietoelementti on annettava kullekin aineistolle.
|===

[#taulukko-download-protocol]
.Rajapintapalvelukohtaiset protokollatunnukset
[width="90%",cols="3,5"]
|===
|*Rajapintapalvelun tyyppi* {set:cellbgcolor:#e9e9e9}| *Protokollatunnus*
|INSPIRE Pre-defined Dataset WFS 2.0 {set:cellbgcolor:#FFFFFF} | http://inspire.ec.europa.eu/id/ats/download-service/3.1/predefined-wfs
|INSPIRE Direct Access WFS 2.0 | http://inspire.ec.europa.eu/id/ats/download-service/3.1/direct-wfs
|INSPIRE Pre-defined Dataset Atom | http://inspire.ec.europa.eu/id/ats/download-service/3.1/predefined-atom
|INSPIRE WCS 2.0 Mandatory Download Operations | http://inspire.ec.europa.eu/id/ats/download-service-wcs/1.0/wcs-man
|INSPIRE WCS 2.0 Direct Access Download Operations | http://inspire.ec.europa.eu/id/ats/download-service-wcs/1.0/wcs-con
|INSPIRE Pre-defined Dataset SOS 2.0 | http://inspire.ec.europa.eu/id/ats/download-service-sos/1.0/predefined-sos
|INSPIRE Direct Access SOS 2.0 | http://inspire.ec.europa.eu/id/ats/download-service-sos/1.0/direct-sos
|===

[#vaatimus-latauspalvelu-linkki-predefined-wfs]
[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{x-vaatimus-latauspalvelu-linkki-predefined-wfs-nro}* {set:cellbgcolor:#e7e6c8}| `vaatimukset/vaatimus-latauspalvelu-linkki-predefined-wfs` +
{set:cellbgcolor:#FFFFFF}

Mikäli Vaatimuksen {x-vaatimus-latauspalvelu-linkki-nro} mukainen linkki rajapintapalveluun on tyyppiä INSPIRE Pre-defined Dataset WFS 2.0,
tulee XPath-kyselyn +
`/pass:[*]/gmd:distributionInfo[1]/pass:[*]/gmd:transferOptions/pass:[*]/gmd:onLine/pass:[*][./gmd:linkage/gmd:URL and ./gmd:function/gmd:CI_OnLineFunctionCode/@codeListValue='download' and ./gmd:protocol/gmx:Anchor/@xlink:href='http://inspire.ec.europa.eu/id/ats/download-service/3.1/predefined-wfs']/gmd:name/gco:CharacterString/text()`
palauttaa aineiston INSPIRE-tunnus. Tämän tunnuksen avulla kyseisestä WFS-rajapalvelusta voidaan hakea metatiedon
kuvaama aineisto tallennetun kyselyn avulla <<TG_DS_31>>:n vaatimusten TG Requirement 49, 50 ja 51 mukaisesti.
|===

.Esimerkki{nbsp}{counter:example}: Linkitys INSPIRE Pre-defined Dataset WFS 2.0 -palveluun
[source,xml]
----
<gmd:transferOptions>
  <gmd:MD_DigitalTransferOptions>
     <gmd:onLine>
        <gmd:CI_OnlineResource>
           <gmd:linkage>
              <gmd:URL>https://lataus.paikkatietoikkuna.fi/wfs?</gmd:URL>
           </gmd:linkage>
           <gmd:protocol>
              <gmx:Anchor
                 xlink:href="http://inspire.ec.europa.eu/id/ats/download-service/3.1/predefined-wfs">INSPIRE Pre-defined Dataset WFS 2.0</gmx:Anchor>
           </gmd:protocol>
           <gmd:name>
              <gco:CharacterString>http://paikkatiedot.fi/so/1002200/ps/ProtectedSites</gco:CharacterString>
           </gmd:name>
           <gmd:function>
              <gmd:CI_OnLineFunctionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#CI_OnlineFunctionCode" codeListValue="download">Download</gmd:CI_OnLineFunctionCode>
           </gmd:function>
        </gmd:CI_OnlineResource>
     </gmd:onLine>
  </gmd:MD_DigitalTransferOptions>
</gmd:transferOptions>
----

[#vaatimus-latauspalvelu-linkki-predefined-atom]
[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{x-vaatimus-latauspalvelu-linkki-predefined-atom-nro}* {set:cellbgcolor:#e7e6c8}| `vaatimukset/vaatimus-latauspalvelu-linkki-predefined-atom` +
{set:cellbgcolor:#FFFFFF}

Mikäli Vaatimuksen {x-vaatimus-latauspalvelu-linkki-nro} mukainen linkki rajapintapalveluun on tyyppiä INSPIRE Pre-defined Dataset Atom,
tulee XPath-kyselyn +
`/pass:[*]/gmd:distributionInfo[1]/pass:[*]/gmd:transferOptions/pass:[*]/gmd:onLine/pass:[*][./gmd:linkage/gmd:URL and ./gmd:function/gmd:CI_OnLineFunctionCode/@codeListValue='download' and ./gmd:protocol/gmx:Anchor/@xlink:href='http://inspire.ec.europa.eu/id/ats/download-service/3.1/predefined-atom']/gmd:name/gco:CharacterString/text()`
palauttaa <<TG_DS_31>>:n
vaatimuksen TG Requirement 9 mukainen metatiedon kuvaaman aineiston entry:n tunnus (`id`) Atom-palvelun
Download Service -syötteessä.
|===

.Esimerkki{nbsp}{counter:example}: Linkitys INSPIRE Pre-defined Dataset Atom -palveluun
[source,xml]
----
<gmd:transferOptions>
  <gmd:MD_DigitalTransferOptions>
     <gmd:onLine>
        <gmd:CI_OnlineResource>
           <gmd:linkage>
              <gmd:URL>http://wwwd3.ymparisto.fi/d3/INSPIREAtom/inspireatomgml.xml</gmd:URL>
           </gmd:linkage>
           <gmd:protocol>
              <gmx:Anchor
                 xlink:href="http://inspire.ec.europa.eu/id/ats/download-service/3.1/predefined-atom">INSPIRE Pre-defined Dataset Atom</gmx:Anchor>
           </gmd:protocol>
           <gmd:name>
              <gco:CharacterString>PS_luonnonsuojelualueet</gco:CharacterString>
           </gmd:name>
           <gmd:function>
              <gmd:CI_OnLineFunctionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#CI_OnlineFunctionCode"
                 codeListValue="download">Download</gmd:CI_OnLineFunctionCode>
           </gmd:function>
        </gmd:CI_OnlineResource>
     </gmd:onLine>
  </gmd:MD_DigitalTransferOptions>
</gmd:transferOptions>
----

[#vaatimus-latauspalvelu-linkki-wcs]
[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{x-vaatimus-latauspalvelu-linkki-wcs-nro}* {set:cellbgcolor:#e7e6c8}| `vaatimukset/vaatimus-latauspalvelu-linkki-wcs` +
{set:cellbgcolor:#FFFFFF}

Mikäli Vaatimuksen {x-vaatimus-latauspalvelu-linkki-nro} mukaisen linkin osoittama rajapintapalvelu on tyyppiä OGC Web Coverage Service (WCS),
tulee XPath-kyselyn +
`/pass:[*]/gmd:distributionInfo[1]/pass:[*]/gmd:transferOptions/pass:[*]/gmd:onLine/pass:[*][./gmd:linkage/gmd:URL and ./gmd:function/gmd:CI_OnLineFunctionCode/@codeListValue='download' and /gmd:protocol/gmx:Anchor/starts-with(@xlink:href,'http://inspire.ec.europa.eu/id/ats/download-service-wcs/')]/gmd:name/gco:CharacterString/text()`
palauttaa metatiedon kuvaaman aineiston `coverageId` <<WCS_20>>:n vaatimuksen Requirement 22 mukaisesti.
|===

.Esimerkki{nbsp}{counter:example}: Linkitys WCS-palveluun
[source,xml]
----
<gmd:transferOptions>
  <gmd:MD_DigitalTransferOptions>
     <gmd:onLine>
        <gmd:CI_OnlineResource>
           <gmd:linkage>
              <gmd:URL>https://lataus.paikkatietoikkuna.fi/wcs?</gmd:URL>
           </gmd:linkage>
           <gmd:protocol>
              <gmx:Anchor
                 xlink:href="http://inspire.ec.europa.eu/id/ats/download-service-wcs/1.0/wcs-con">INSPIRE WCS 2.0 Direct Access Download Operations</gmx:Anchor>
           </gmd:protocol>
           <gmd:name>
              <gco:CharacterString>ortoCov1234</gco:CharacterString>
           </gmd:name>
           <gmd:function>
              <gmd:CI_OnLineFunctionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#CI_OnlineFunctionCode"
                 codeListValue="download">Download</gmd:CI_OnLineFunctionCode>
           </gmd:function>
        </gmd:CI_OnlineResource>
     </gmd:onLine>
  </gmd:MD_DigitalTransferOptions>
</gmd:transferOptions>
----

[#vaatimus-latauspalvelu-linkki-sos]
[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{x-vaatimus-latauspalvelu-linkki-sos-nro}* {set:cellbgcolor:#e7e6c8}| `vaatimukset/vaatimus-latauspalvelu-linkki-sos` +
{set:cellbgcolor:#FFFFFF}

Mikäli Vaatimuksen {x-vaatimus-latauspalvelu-linkki-nro} mukaisen linkin osoittama rajapintapalvelu on tyyppiä OGC Sensor Observation Service (SOS),
tulee XPath-kyselyn +
`/pass:[*]/gmd:distributionInfo[1]/pass:[*]/gmd:transferOptions/pass:[*]/gmd:onLine/pass:[*][./gmd:linkage/gmd:URL and ./gmd:function/gmd:CI_OnLineFunctionCode/@codeListValue='download' and /gmd:protocol/gmx:Anchor/starts-with(@xlink:href,'http://inspire.ec.europa.eu/id/ats/download-service-sos/')]/gmd:name/gco:CharacterString/text()`
palauttaa metatiedon kuvaaman aineiston ObservationOffering identifier <<SOS_20>>:n vaatimuksen Requirement 21 mukaisesti.
|===

==== Aineiston siirto- tai tallennusmuoto
INSPIRE-vaatimus TG Requirement 2.6 vaatii kuvaamaan metatiedossa ne siirto- tai tallennusmuodot (formaatit),
joiden mukaisesti koodattuna aineisto on ladattavissa. PTA-aineistoille ei aseteta erityisiä vaatimuksia
tämän INSPIRE-vaatimuksen lisäksi.

=== Laatutiedot (dataQualityInfo)
Alla on listattu laatutietoihin
liittyvät INSPIRE-vaatimukset. Näiden vaatimusten tarkemmat kuvaukset löytyvät
dokumentista <<TG_MD_20>>.

.Laatutietoihin kohdistuvat INSPIRE-vaatimukset
[cols="1,4",width="90%"]
|===
|*Numero* {set:cellbgcolor:#e9e9e9}| *Tunnus*
|TG{nbsp}Requirement{nbsp}C.20 {set:cellbgcolor:#FFFFFF}| http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/conformity
|TG{nbsp}Requirement{nbsp}C.21 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/conformity-specification
|TG{nbsp}Requirement{nbsp}C.22 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/common/conformity-degree
|TG{nbsp}Requirement{nbsp}1.9 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/one-data-quality-element
|TG{nbsp}Requirement{nbsp}1.10 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/conformity
|TG{nbsp}Requirement{nbsp}1.11 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/datasets-and-series/lineage
|TG{nbsp}Requirement{nbsp}2.7 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/isdss/topological-consistency-quantitative-results
|TG{nbsp}Requirement{nbsp}2.8 | http://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/req/isdss/topological-consistency-descriptive-results
|===

PTA-aineistojen suhteen esitetään lisäksi tämän luvun sisältämät lisävaatimukset.

[#vaatimus-pta-vaatimuksenmukaisuus]
[width="90%",cols="2,6"]
|===
|*Vaatimus{nbsp}{x-vaatimus-pta-vaatimuksenmukaisuus-nro}* {set:cellbgcolor:#e7e6c8}| `vaatimukset/vaatimus-pta-vaatimuksenmukaisuus` +
{set:cellbgcolor:#FFFFFF}
PTA-aineistojen metatietoihin tulee kirjata merkinnät
PTA-vaatimuksenmukaisuusluokkien sisältävien laatutestien tuloksista. Metatiedon tulee sisältää yksi
vaatimuksenmukaisuusmerkintä kutakin kyseiselle aineistolle pakollista vaatimuksenmukaisuusluokkaa kohti.
XPath-kyselyn
`/pass:[*]/gmd:dataQualityInfo/pass:[*]/gmd:report/gmd:DQ_DomainConsistency/gmd:result/gmd:DQ_ConformanceResult
[./gmd:specification/pass:[*]/gmd:title/gmx:Anchor/starts-with(@xlink:href,'http://paikkatietoalusta.fi/id/vaatimuksenmukaisuusluokka/')]
/gmd:pass/gco:Boolean/text()` tulee palauttaa kaikkien PTA-laatutestien vaatimuksenmukaisuusmerkintöjen läpäisystä kertovat
totuusarvot (true/false).
|===

Aineiston läpäisemien PTA-vaatimuksenmukaisuustestien tuloksia voidaan yhdessä käyttää aineistojen yhteismitallisen
laatuluokituksen laskemiseen.

[NOTE]
====
PTA-vaatimuksenmukaisuusluokkien ja niihin kuuluvien PTA-laatuvahti -palvelun testien määrittely ei kuulu tämän
dokumentin piiriin.

====

.Esimerkki{nbsp}{counter:example}: PTA-laatuvahdin testituloksen perusteella tuotettu tulos: aineisto on kuviteellisen vaatimuksenmukaisuusluokan Topologia mukainen. Huomaa, että päivämäärä on kyseisen vaatimuksenmukaisuusluokan julkaisupäivä, ei testin ajopäivä.
[source,xml]
----
<gmd:report>
  <gmd:DQ_DomainConsistency>
     <gmd:result>
        <gmd:DQ_ConformanceResult>
           <gmd:specification>
              <gmd:CI_Citation>
                 <gmd:title>
                    <gmx:Anchor xlink:href="http://paikkatietoalusta.fi/id/vaatimuksenmukaisuusluokka/topologia">Topologia</gmx:Anchor>
                 </gmd:title>
                 <gmd:date>
                    <gmd:CI_Date>
                       <gmd:date>
                          <gco:Date>2018-11-02</gco:Date>
                       </gmd:date>
                       <gmd:dateType>
                          <gmd:CI_DateTypeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#CI_DateTypeCode"
                             codeListValue="publication"/>
                       </gmd:dateType>
                    </gmd:CI_Date>
                 </gmd:date>
              </gmd:CI_Citation>
           </gmd:specification>
           <gmd:explanation>
              <gco:CharacterString>Sisältää geometrioihin ja topologiaan liittyviä testejä. Läpäisy tarkoittaa, että aineiston kohteiden geometrioissa ei ole testien havaitsemia ongelmia.</gco:CharacterString>
           </gmd:explanation>
           <gmd:pass>
              <gco:Boolean>true</gco:Boolean>
           </gmd:pass>
        </gmd:DQ_ConformanceResult>
     </gmd:result>
  </gmd:DQ_DomainConsistency>
</gmd:report>
----

[#suositus-yksityiskohtaisuus-luokittelu]
[width="90%",cols="2,6"]
|===
|*Suositus{nbsp}{x-suositus-yksityiskohtaisuus-luokittelu-nro}* | `vaatimukset/suositus-yksityiskohtaisuus-luokittelu` +
Mikäli aineiston yksityiskohtaisuuden kuvaamiseen on käytettävissä yleisesti käytetty luokittelu, on suositeltavaa ilmaista kuvattavan aineiston yksityiskohtaisuuden taso
 vaatimuksenmukaisuusviittauksella kyseiseen luokitteluun laatutietoelementin alla:
 `/pass:[*]/gmd:dataQualityInfo/pass:[*]/gmd:report/gmd:DQ_DomainConsistency/gmd:result/gmd:DQ_ConformanceResult`
|===
