== Velvoittavat viittaukset
Seuraavat normatiiviset asiakirjat sisältävät vaatimuksia ja ehtoja, jotka viittausten kautta ovat
muodostavat erottamattoman osan tämän dokumentin vaatimuksia. Päivättyjen viitteiden osalta asiakirjojen
mahdollisia kyseisen päivän jälkeen julkaistuja lisäyksiä tai korjauksia ei oteta huomioon. Päiväämättömien
viittausten osalta tarkoitetaan kyseisen asiankirjan viimeisintä julkaistua versiota.

<<ISO_19115>> EN ISO 19115: 2005, Geographic information - Metadata

<<ISO_19139>> ISO/TS 19139: 2007, Geographic information - Metadata - XML schema implementation

<<ISO_19105>> EN ISO 19105:2005, Geographic Information – Conformance and testing (ISO 19105:2000)

<<ISO_639-2>> ISO 639-2:1998, Codes for the representation of names of languages – Part 2: Alpha-3 code

<<INSPIRE>> Directive 2007/2/EC of the European Parliament and of the Council of 14 March
2007 establishing an Infrastructure for Spatial Information in the European Community (INSPIRE)

<<IR_Metadata>> Commission Regulation (EC) No 1205/2008 of 3 December 2008
implementing Directive 2007/2/EC of the European Parliament and of the Council as regards
metadata.

<<IR-ISDSS>> Commission Regulation (EU) No 1089/2010 of 23 November 2010
implementing Directive 2007/2/EC of the European Parliament and of the Council as regards
interoperability of spatial data sets and services, as amended by

* Commission Regulation (EU) No 102/2011 of 4 February 2011 amending Regulation (EU) No
1089/2010 implementing Directive 2007/2/EC of the European Parliament and of the Council
as regards interoperability of spatial data sets and services;
* Commission Regulation (EU) No 1253/2013 of 21 October 2013 amending Regulation (EU)
No 1089/2010 implementing Directive 2007/2/EC as regards interoperability of spatial data
sets and services; and
* Commission Regulation (EU) No 1312/2014 of 10 December 2014 amending Regulation (EU)
No 1089/2010 implementing Directive 2007/2/EC of the European Parliament and of the
Council as regards interoperability of spatial data services.

<<TG_MD_20>> Technical Guidance for the implementation of INSPIRE dataset and service metadata based on ISO/TS 19139:2007, version 2.0, https://inspire.ec.europa.eu/id/document/tg/metadata-iso19139

<<JHS_158>> JHS 158 Paikkatietoaineistojen ja -palveluiden metatiedot, vuoden 2018 versio, http://www.jhs-suositukset.fi/suomi/jhs158
